"site_name": "mno"
"site_schemas": "../site_schemas.yaml"

# "output_corpus": "mno_corpus.txt"
# "tags": "tags.yaml"

"log_file_articles": "logs/mno_ahelyzet_articles_log.txt"
"log_file_archive": "logs/mno_ahelyzet_archive_log.txt"
"new_problematic_urls": "logs/mno_ahelyzet_new_problematic_urls.txt"
"new_good_urls": "logs/mno_ahelyzet_new_good_urls.txt"
"new_problematic_archive_urls": "logs/mno_ahelyzet_new_problematic_archive_urls.txt"
"new_good_archive_urls": "logs/mno_ahelyzet_new_good_archive_urls.txt"

# "date_from": 2019-02-06   # First article
# "date_until": 2019-10-03  # Last article

"initial_pagenum": 1
"min_pagenum": 2
"archive_url_format": "https://magyarnemzet.hu/ahelyzet/page/#pagenum/"
"max_pagenum": 20
