"site_name": "valasz"
"site_schemas": "../site_schemas.yaml"

# "output_corpus": "valasz_corpus.txt"
# "tags": "tags.yaml"

"log_file_articles": "logs/valasz_kultura_articles_log.txt"
"log_file_archive": "logs/valasz_kultura_archive_log.txt"
"new_problematic_urls": "logs/valasz_kultura_new_problematic_urls.txt"
"new_good_urls": "logs/valasz_kultura_new_good_urls.txt"
"new_problematic_archive_urls": "logs/valasz_kultura_new_problematic_archive_urls.txt"
"new_good_archive_urls": "logs/valasz_kultura_new_good_archive_urls.txt"

# "date_from": 2013-09-30   # First article
# "date_until": 2019-02-13  # Last article

"archive_url_format": "http://valasz.hu/kultura?page=#pagenum"
"max_pagenum": 1693