"site_name": "24hu"

"columns":
    "belfold":
        "archive_url_format": "https://24.hu/belfold/page/#pagenum"

        "date_first_article": 0001-01-01
        #"date_last_article": 2019-12-31

        "initial_pagenum": 1
        "min_pagenum": 2
        "max_pagenum": 3  # TODO: 10500 jelenleg.

    "kulfold":
        "archive_url_format": "https://24.hu/kulfold/page/#pagenum"

        "date_first_article": 0001-01-01
        #"date_last_article": 2019-12-31

        "initial_pagenum": 1
        "min_pagenum": 2
        "max_pagenum": 3  # TODO: 4556 jelenleg.

"portal_specific_exctractor_functions_file": "../extractors/site_specific_extractor_functions.py"
# "extract_next_page_url_fun": "extract_next_page_url_24hu"
"extract_article_urls_from_page_fun": "extract_article_urls_from_page_24hu"

"next_url_by_pagenum": true
"infinite_scrolling": false
"archive_page_urls_by_date": false
"go_reverse_in_archive": true
"verify_request": false
"ignore_archive_cache": true  # TODO: átállítani.

# "new_article_url_threshold": 0

"corpus_converter_file": "../extractors/corpus_converters.py"
"corpus_converter": "dummy-converter"
