"site_name": "24hu"

"columns":
    "belfold":
        "archive_url_format": "https://24.hu/belfold/#year/#month/#day/"

        "date_first_article": 2000-01-01

    "belfold-old1":
        "archive_url_format": "https://24.hu/belfold/#year/#month/#day/"

        "date_first_article": 1997-11-04
        "date_last_article":  1997-11-05

    "belfold-old2":
        "archive_url_format": "https://24.hu/belfold/#year/#month/#day/"

        "date_first_article": 1990-11-02
        "date_last_article":  1990-11-03

    "belfold-old3":
        "archive_url_format": "https://24.hu/belfold/#year/#month/#day/"

        "date_first_article": 1848-12-15
        "date_last_article":  1848-12-16

    "belfold-old4":
        "archive_url_format": "https://24.hu/belfold/#year/#month/#day/"

        "date_first_article": 0001-01-01
        "date_last_article":  0001-01-02

    "kulfold":
        "archive_url_format": "https://24.hu/kulfold/#year/#month/#day/"

        "date_first_article": 2001-03-27

    "kulfold-old1":
        "archive_url_format": "https://24.hu/kulfold/#year/#month/#day/"

        "date_first_article": 0001-01-01
        "date_last_article":  0001-01-02

    "gazdasag":
        "archive_url_format": "https://24.hu/fn/gazdasag/#year/#month/#day/"

        "date_first_article": 1996-01-03

    "gazdasag-old1":
        "archive_url_format": "https://24.hu/fn/gazdasag/#year/#month/#day/"

        "date_first_article": 0001-01-01
        "date_last_article":  0001-01-02

    "kultura":
        "archive_url_format": "https://24.hu/kultura/#year/#month/#day/"

        "date_first_article": 2010-04-08

    "kultura-old1":
        "archive_url_format": "https://24.hu/kultura/#year/#month/#day/"

        "date_first_article": 0001-01-01
        "date_last_article":  0001-01-02

    "tech":
        "archive_url_format": "https://24.hu/tech/#year/#month/#day/"

        "date_first_article": 2010-04-15

    "elet-stilus":
        "archive_url_format": "https://24.hu/elet-stilues/#year/#month/#day/"

        "date_first_article": 2001-01-17

    "elet-stilus-old1":
        "archive_url_format": "https://24.hu/elet-stilues/#year/#month/#day/"

        "date_first_article": 2000-06-07
        "date_last_article":  2000-06-08

    "elet-stilus-old2":
        "archive_url_format": "https://24.hu/elet-stilues/#year/#month/#day/"

        "date_first_article": 1956-10-28
        "date_last_article":  1956-10-31

    "elet-stilus-old3":
        "archive_url_format": "https://24.hu/elet-stilues/#year/#month/#day/"

        "date_first_article": 1910-11-24
        "date_last_article":  1910-11-25

    "elet-stilus-old4":
        "archive_url_format": "https://24.hu/elet-stilues/#year/#month/#day/"

        "date_first_article": 0001-01-01
        "date_last_article":  0001-01-02

    "kozelet":
        "archive_url_format": "https://24.hu/kozelet/#year/#month/#day/"

        "date_first_article": 2010-03-02

    "uzleti-tippek":
        "archive_url_format": "https://24.hu/fn/uzleti-tippek/#year/#month/#day/"

        "date_first_article": 2001-02-03

    "uzleti-tippek-old1":
        "archive_url_format": "https://24.hu/fn/uzleti-tippek/#year/#month/#day/"

        "date_first_article": 1996-01-01
        "date_last_article":  1996-01-02

    "uzleti-tippek-old2":
        "archive_url_format": "https://24.hu/fn/uzleti-tippek/#year/#month/#day/"

        "date_first_article": 0001-01-01
        "date_last_article":  0001-01-02

    "szorakozas":
        "archive_url_format": "https://24.hu/szorakozas/#year/#month/#day/"

        "date_first_article": 2010-03-01

    "szorakozas-old1":
        "archive_url_format": "https://24.hu/szorakozas/#year/#month/#day/"

        "date_first_article": 0001-01-01
        "date_last_article":  0001-01-02

    # The "europoli" column's articles link to articles in the main columns (e.g. belfold, kulfold, etc.). No need to download these again.

    "tudomany":
        "archive_url_format": "https://24.hu/tudomany/#year/#month/#day/"

        "date_first_article": 2010-03-01

    "sport":
        "archive_url_format": "https://24.hu/sport/#year/#month/#day/"

        "date_first_article": 2011-09-27

    "otthon":
        "archive_url_format": "https://24.hu/otthon/#year/#month/#day/"

        "date_first_article": 2017-05-01

    # The "velemeny" column's articles link to articles in the main columns (e.g. belfold, kulfold, etc.). No need to download these again.

    # The "video" column's articles link to articles in the main columns (e.g. belfold, kulfold, etc.). No need to download these again.

    # The "podcast" column's articles link to articles in the main columns (e.g. belfold, kulfold, etc.). No need to download these again.

"portal_specific_exctractor_functions_file": "../extractors/site_specific_extractor_functions.py"
"extract_next_page_url_fun": "extract_next_page_url_24hu"
"extract_article_urls_from_page_fun": "extract_article_urls_from_page_24hu"

"next_url_by_pagenum": false
"infinite_scrolling": false
"archive_page_urls_by_date": true
"go_reverse_in_archive": false
"verify_request": true
"ignore_archive_cache": false

# "new_article_url_threshold": 0

"corpus_converter_file": "../extractors/corpus_converters.py"
"corpus_converter": "dummy-converter"
