"site_name": "444"

"columns":
    "main-column":
        "archive_url_format": "https://444.hu/#year/#month/#day/"

        "date_first_article": 2013-04-10
        # "date_last_article":  2100-01-01

        "min_pagenum": 0
        # "max_pagenum": NULL

"portal_specific_exctractor_functions_file": "../extractors/site_specific_extractor_functions.py"
"extract_next_page_url_fun": "extract_next_page_url_444"
"extract_article_urls_from_page_fun": "extract_article_urls_from_page_444"
"next_page_of_article_fun": "next_page_of_article_444"

"next_url_by_pagenum": true
"infinite_scrolling": false
"archive_page_urls_by_date": true
"go_reverse_in_archive": true
"verify_request": true
"ignore_archive_cache": false

# "new_article_url_threshold": 0

"corpus_converter_file": "../extractors/corpus_converters.py"
"corpus_converter": "MultiPageArticleConverter"
