"site_name": "alfahir"

"columns":
    "main-column-from-2011-12-31-to-2012-02-29":
        "archive_url_format": "https://alfahir.hu/kereso?kereses=&from=#year-#month-#day&to=#year-#month-#day"

        "date_first_article": 2011-12-31
        "date_last_article": 2012-02-29

    # This time period has few articles, so a monthly approach is used.
    "main-column-from-2012-03-01-to-2012-07-01":
        "archive_url_format": "https://alfahir.hu/kereso?kereses=&from=#year-#month-01&to=#next-year-#next-month-01"

        "date_first_article": 2012-03-01
        "date_last_article": 2012-06-30

    "main-column-from-2012-07-02-to-now":
        "archive_url_format": "https://alfahir.hu/kereso?kereses=&from=#year-#month-#day&to=#year-#month-#day"

        "date_first_article": 2012-07-02

"portal_specific_exctractor_functions_file": "../extractors/site_specific_extractor_functions_news_ngvmt.py"
"extract_next_page_url_fun": "extract_next_page_url_alfahir"
"extract_article_urls_from_page_fun": "extract_article_urls_from_page_alfahir"

"next_url_by_pagenum": false
"infinite_scrolling": false
"archive_page_urls_by_date": true
"go_reverse_in_archive": false
"verify_request": true
"ignore_archive_cache": false

"corpus_converter_file": "../extractors/corpus_converters.py"
"corpus_converter": "dummy-converter"
