"site_name": "atlatszo_ro"

"columns":
    "hu":
        "archive_url_format": "https://atlatszo.ro/page/#pagenum/?s"

        # "date_first_article": 2015-08-20
        # "date_last_article": 2020-12-17

        "initial_pagenum": 1
        #"min_pagenum": 1
        #"max_pagenum": 1
    "ro":
        "archive_url_format": "https://atlatszo.ro/ro/page/#pagenum/?s"

        # "date_first_article": 2015-08-20
        # "date_last_article": 2020-12-17

        "initial_pagenum": 1
        # "min_pagenum": 2
        # "max_pagenum": 31
    "en":
        "archive_url_format": "https://atlatszo.ro/en/page/#pagenum/?s"

        # "date_first_article": 2015-08-20
        # "date_last_article": 2020-12-17

        "initial_pagenum": 1
        # "min_pagenum": 2
        # "max_pagenum": 31

"portal_specific_exctractor_functions_file": "../extractors/site_specific_extractor_functions.py"
#"extract_next_page_url_fun": "extract_next_page_url_atlatszo_ro"
"extract_article_urls_from_page_fun": "extract_article_urls_from_page_atlatszo_ro"

"next_url_by_pagenum": true
"infinite_scrolling": true
"archive_page_urls_by_date": false
"go_reverse_in_archive": true
"verify_request": false
"ignore_archive_cache": false

# "new_article_url_threshold": 0

"corpus_converter_file": "../extractors/corpus_converters.py"
"corpus_converter": "dummy-converter"
