"site_name": "gov_koronavirus"

"columns":
    "main-column":
        "archive_url_format": "https://www.nnk.gov.hu/index.php/jarvanyugyi-es-infekciokontroll-foosztaly/lakossagi-tajekoztatok/koronavirus"

        # "date_first_article": 2020-01-22
        # "date_last_article": 2020-12-18

        "initial_pagenum": 1
        # "min_pagenum": 2
        # "max_pagenum": 8

"portal_specific_exctractor_functions_file": "../extractors/site_specific_extractor_functions.py"
"extract_next_page_url_fun": "extract_next_page_url_gov_koronavirus"
"extract_article_urls_from_page_fun": "extract_article_urls_from_page_gov_koronavirus"

"next_url_by_pagenum": false
"infinite_scrolling": false
"archive_page_urls_by_date": false
"go_reverse_in_archive": true
"verify_request": false
"ignore_archive_cache": false

# "new_article_url_threshold": 0

"corpus_converter_file": "../extractors/corpus_converters.py"
"corpus_converter": "dummy-converter"
