"site_name": "jogtar"

"columns":
    "main-column":
        "archive_url_format": "https://net.jogtar.hu/jogszabaly-kereso?sorszam=&para=&tipus=&evszam=#year"

        "date_first_article": 1900-01-01
        # "date_last_article": 2100-01-01

        "min_pagenum": 0
        # "max_pagenum": NULL

"portal_specific_exctractor_functions_file": "../extractors/site_specific_extractor_functions.py"
"extract_article_urls_from_page_fun": "extract_article_urls_from_page_index"

"next_url_by_pagenum": false
"infinite_scrolling": false
"archive_page_urls_by_date": true
"go_reverse_in_archive": true
"verify_request": true
"ignore_archive_cache": false

# "new_article_url_threshold": 0

"corpus_converter_file": "../extractors/corpus_converters.py"
"corpus_converter": "dummy-converter"
