"site_name": "kuruc"

# It is a column-based archive. Duplications may occur if an article is in more than one column.

"columns":
    "main-column":
        "archive_url_format": "https://kuruc.info/to/1/10/"

    "friss_hirek":
        "archive_url_format": "https://kuruc.info/t/1/"

    "anyaorszag":
        "archive_url_format": "https://kuruc.info/t/2/"

    "elcsatolt_reszek":
        "archive_url_format": "https://kuruc.info/t/3/"

    "kulfold":
        "archive_url_format": "https://kuruc.info/t/4/"

    "extra":
        "archive_url_format": "https://kuruc.info/t/6/"

    "publicisztika":
        "archive_url_format": "https://kuruc.info/t/7/"

    "lapszemle":
        "archive_url_format": "https://kuruc.info/t/8/"

    "tanulmanyok":
        "archive_url_format": "https://kuruc.info/t/9/"

    "olvasoi_levelek":
        "archive_url_format": "https://kuruc.info/t/20/"

    "jo_es_szep":
        "archive_url_format": "https://kuruc.info/t/21/"

    "humor":
        "archive_url_format": "https://kuruc.info/t/22/"

    "programajanlo":
        "archive_url_format": "https://kuruc.info/t/23/"

    "antimagyarizmus":
        "archive_url_format": "https://kuruc.info/t/26/"

    "video":
        "archive_url_format": "https://kuruc.info/t/34/"

    "cigany_b":
        "archive_url_format": "https://kuruc.info/t/35/"

    "rendor_b":
        "archive_url_format": "https://kuruc.info/t/37/"

    "mozi":
        "archive_url_format": "https://kuruc.info/t/38/"

    "zsido_b":
        "archive_url_format": "https://kuruc.info/t/39/"

    "english":
        "archive_url_format": "https://kuruc.info/t/40/"

    "gazdasag":
        "archive_url_format": "https://kuruc.info/t/42/"

    "gentemeto":
        "archive_url_format": "https://kuruc.info/t/46/"

    "sport":
        "archive_url_format": "https://kuruc.info/t/49/"

    "reklam":
        "archive_url_format": "https://kuruc.info/t/50/"

    "valasztas_2010":
        "archive_url_format": "https://kuruc.info/t/52/"

    "politikus_b":
        "archive_url_format": "https://kuruc.info/t/53/"

    "olimpia_2012":
        "archive_url_format": "https://kuruc.info/t/54/"

    "holokamu":
        "archive_url_format": "https://kuruc.info/t/56/"

    "valasztas_2014":
        "archive_url_format": "https://kuruc.info/t/57/"

    "tudomany_technika":
        "archive_url_format": "https://kuruc.info/t/58/"

    "bevandorlo_b":
        "archive_url_format": "https://kuruc.info/t/59/"

    "igy_irtak_ok":
        "archive_url_format": "https://kuruc.info/t/61/"

    "kultura":
        "archive_url_format": "https://kuruc.info/t/62/"

    "koronavirus":
        "archive_url_format": "https://kuruc.info/t/64/"

    "lmbtqp":
        "archive_url_format": "https://kuruc.info/t/66/"


"portal_specific_exctractor_functions_file": "../extractors/site_specific_extractor_functions_kuruc_vadh.py"
"extract_next_page_url_fun": "extract_next_page_url_kuruc"
"extract_article_urls_from_page_fun": "extract_article_urls_from_page_kuruc"

"next_url_by_pagenum": false
"infinite_scrolling": false
"archive_page_urls_by_date": false
"go_reverse_in_archive": false
"verify_request": true
"ignore_archive_cache": false

# "new_article_url_threshold": 0

"corpus_converter_file": "../extractors/corpus_converters.py"
"corpus_converter": "dummy-converter"
