"site_name": "magyaridok"
"date_first_article": 2015-04-21
"date_last_article": 2019-05-15
"archive_url_format": "https://www.magyaridok.hu/page/#pagenum/?after=2015-04-20&author&before=2019-05-15&category=0&s"

"extract_next_page_url_fun": NULL
"extract_article_urls_from_page_fun": "extract_article_urls_from_page_magyaridok"
"next_url_by_pagenum": true
"infinite_scrolling": false
"archive_page_urls_by_date": false
"go_reverse_in_archive": true
"verify_request": false

"initial_pagenum": 1
"min_pagenum": 2
"max_pagenum": 8291

"ignore_archive_cache": false
# "new_article_url_threshold": 0
"follow_links_on_page": false

"corpus_converter": "dummy-converter"

# "tags_keys":
#     "^http://www\\.magyaridok\\.hu/": NULL
