"site_name": "magyarnarancs"

# In the beginning of the archive, articles appear only one day per week. Because of that, we iterate the archive by month.

"columns":
    "main-column":
        "archive_url_format": "https://magyarnarancs.hu/kereses?search_txt=.&search_szerzo=&search_idoszak_tol=#year-#month-02&search_idoszak_ig=#next-year-#next-month-01"

        "date_first_article": 1996-05-09

"portal_specific_exctractor_functions_file": "../extractors/site_specific_extractor_functions_news_ngvmt.py"
"extract_next_page_url_fun": "extract_next_page_url_magyarnarancs"
"extract_article_urls_from_page_fun": "extract_article_urls_from_page_magyarnarancs"

"next_url_by_pagenum": false
"infinite_scrolling": false
"archive_page_urls_by_date": true
"go_reverse_in_archive": false
"verify_request": true
"ignore_archive_cache": false

# "new_article_url_threshold": 0

"corpus_converter_file": "../extractors/corpus_converters.py"
"corpus_converter": "dummy-converter"
