"site_name": "maszol"

"columns":
    "belfold":
        "archive_url_format": "https://maszol.ro/belfold/"

    "gazdasag":
        "archive_url_format": "https://maszol.ro/gazdasag/"

    "kultura":
        "archive_url_format": "https://maszol.ro/kultura/"

    "velemeny":
        "archive_url_format": "https://maszol.ro/velemeny/"

    "eletmod":
        "archive_url_format": "https://maszol.ro/eletmod/"

    "kulfold":
        "archive_url_format": "https://maszol.ro/kulfold/"

    "sport":
        "archive_url_format": "https://maszol.ro/sport/"

    "videok":
        "archive_url_format": "https://maszol.ro/videok/"


"portal_specific_exctractor_functions_file": "../extractors/site_specific_extractor_functions.py"
"extract_next_page_url_fun": "extract_next_page_url_maszol"
"extract_article_urls_from_page_fun": "extract_article_urls_from_page_maszol"

"next_url_by_pagenum": false
"infinite_scrolling": false
"archive_page_urls_by_date": false
"go_reverse_in_archive": false
"verify_request": true
"ignore_archive_cache": false

# "new_article_url_threshold": 0

"corpus_converter_file": "../extractors/corpus_converters.py"
"corpus_converter": "dummy-converter"
