"site_name": "merce"

"columns":
    "oktatas":
        "archive_url_format": "https://merce.hu/tag/oktatas/page/#pagenum/"

        # "date_first_article": 2015-08-20
        # "date_last_article": 2020-12-17

        "initial_pagenum": 1
        "min_pagenum": 2
        # "max_pagenum": 31

    "nok":
        "archive_url_format": "https://merce.hu/tag/nok/page/#pagenum/"

        # "date_first_article": 2015-08-20
        # "date_last_article": 2020-12-17

        "initial_pagenum": 1
        "min_pagenum": 2
        # "max_pagenum": 31

    "szegenyseg":
        "archive_url_format": "https://merce.hu/tag/szegenyseg/page/#pagenum/"

        # "date_first_article": 2015-08-20
        # "date_last_article": 2020-12-17

        "initial_pagenum": 1
        "min_pagenum": 2
        # "max_pagenum": 31

    "munka":
        "archive_url_format": "https://merce.hu/tag/munka/page/#pagenum/"

        # "date_first_article": 2015-08-20
        # "date_last_article": 2020-12-17

        "initial_pagenum": 1
        "min_pagenum": 2
        # "max_pagenum": 31

    "media":
        "archive_url_format": "https://merce.hu/tag/media/page/#pagenum/"

        # "date_first_article": 2015-08-20
        # "date_last_article": 2020-12-17

        "initial_pagenum": 1
        "min_pagenum": 2
        # "max_pagenum": 31

    "roma":
        "archive_url_format": "https://merce.hu/tag/roma/page/#pagenum/"

        # "date_first_article": 2015-08-20
        # "date_last_article": 2020-12-17

        "initial_pagenum": 1
        "min_pagenum": 2
        # "max_pagenum": 31

    "egeszsegugy":
        "archive_url_format": "https://merce.hu/tag/egeszsegugy/page/#pagenum/"

        # "date_first_article": 2015-08-20
        # "date_last_article": 2020-12-17

        "initial_pagenum": 1
        "min_pagenum": 2
        # "max_pagenum": 31

    "dolgozok":
        "archive_url_format": "https://merce.hu/tag/dolgozok/page/#pagenum/"

        # "date_first_article": 2015-08-20
        # "date_last_article": 2020-12-17

        "initial_pagenum": 1
        "min_pagenum": 2
        # "max_pagenum": 31

    "kulfold":
        "archive_url_format": "https://merce.hu/tag/kulfold/page/#pagenum/"

        # "date_first_article": 2015-08-20
        # "date_last_article": 2020-12-17

        "initial_pagenum": 1
        "min_pagenum": 2
        # "max_pagenum": 31

    "demokracia":
        "archive_url_format": "https://merce.hu/tag/demokracia/page/#pagenum/"

        # "date_first_article": 2015-08-20
        # "date_last_article": 2020-12-17

        "initial_pagenum": 1
        "min_pagenum": 2
        # "max_pagenum": 31

    "lakhatas":
        "archive_url_format": "https://merce.hu/tag/dolgozok/page/#pagenum/"

        # "date_first_article": 2015-08-20
        # "date_last_article": 2020-12-17

        "initial_pagenum": 1
        "min_pagenum": 2
        # "max_pagenum": 31

    "publi":
        "archive_url_format": "https://merce.hu/tag/publi/page/#pagenum/"

        # "date_first_article": 2015-08-20
        # "date_last_article": 2020-12-17

        "initial_pagenum": 1
        "min_pagenum": 2
        # "max_pagenum": 31

    "tett":
        "archive_url_format": "https://tett.merce.hu/page/#pagenum/"

        # "date_first_article": 2015-08-20
        # "date_last_article": 2020-12-17

        "initial_pagenum": 1
        "min_pagenum": 2
        # "max_pagenum": 31

    "partizan":
        "archive_url_format": "https://partizan.merce.hu/page/#pagenum/"

        # "date_first_article": 2015-08-20
        # "date_last_article": 2020-12-17

        "initial_pagenum": 1
        "min_pagenum": 2
        # "max_pagenum": 31

    "balraat":
        "archive_url_format": "https://balraat.merce.hu/page/#pagenum/"

        # "date_first_article": 2015-08-20
        # "date_last_article": 2020-12-17

        "initial_pagenum": 1
        "min_pagenum": 2
        # "max_pagenum": 31

    "pogi":
        "archive_url_format": "https://pogi.merce.hu/page/#pagenum/"

        # "date_first_article": 2015-08-20
        # "date_last_article": 2020-12-17

        "initial_pagenum": 1
        "min_pagenum": 2
        # "max_pagenum": 31

    "avm":
        "archive_url_format": "https://avm.merce.hu/page/#pagenum/"

        # "date_first_article": 2015-08-20
        # "date_last_article": 2020-12-17

        "initial_pagenum": 1
        "min_pagenum": 2
        # "max_pagenum": 31

"portal_specific_exctractor_functions_file": "../extractors/site_specific_extractor_functions.py"
#"extract_next_page_url_fun": "extract_next_page_url_merce"
"extract_article_urls_from_page_fun": "extract_article_urls_from_page_merce"

"next_url_by_pagenum": true
"infinite_scrolling": true
"archive_page_urls_by_date": false
"go_reverse_in_archive": true
"verify_request": false
"ignore_archive_cache": false

# "new_article_url_threshold": 0

"corpus_converter_file": "../extractors/corpus_converters.py"
"corpus_converter": "dummy-converter"
