"site_name": "neokohn"

"columns":
    "beginning":
        "archive_url_format": "https://neokohn.hu/#year/#month/#day"

        "date_first_article": 2019-01-20
        "date_last_article": 2019-01-20

    "main-column":
        "archive_url_format": "https://neokohn.hu/#year/#month/#day"

        "date_first_article": 2019-02-01
        # There is no article on 02-02 and 02-03.

"portal_specific_exctractor_functions_file": "../extractors/site_specific_extractor_functions_szng.py"
"extract_next_page_url_fun": "extract_next_page_url_neokohn"
"extract_article_urls_from_page_fun": "extract_article_urls_from_page_neokohn"

"next_url_by_pagenum": false
"infinite_scrolling": false
"archive_page_urls_by_date": true
"go_reverse_in_archive": false
"verify_request": true
"ignore_archive_cache": false

# "new_article_url_threshold": 0

"corpus_converter_file": "../extractors/corpus_converters.py"
"corpus_converter": "dummy-converter"
