"site_name": "p24"

"columns":
    # Problematic intervalls are separated and crawler with daily archive
    # to avoid the random ordering of articles with extactly matching date accross archive pages
    "belfold1":
        "archive_url_format": "https://24.hu/belfold/#year/#month/"

        "date_first_article": 2000-01-01
        "date_last_article":  2001-03-31

    "belfold2":
        "archive_url_format": "https://24.hu/belfold/#year/#month/#day/"

        "date_first_article": 2001-04-01
        "date_last_article":  2005-05-31

    # belfold - Empty intervals are avoided with several pseudo-columns.
    "belfold3":
        "archive_url_format": "https://24.hu/belfold/#year/#month/"

        "date_first_article": 2005-06-01
        "date_last_article":  2009-12-31

    "belfold-1997-11":
        "archive_url_format": "https://24.hu/belfold/#year/#month/"

        "date_first_article": 1997-11-01
        "date_last_article":  1997-11-30

    "belfold-1990-11":
        "archive_url_format": "https://24.hu/belfold/#year/#month/"

        "date_first_article": 1990-11-01
        "date_last_article":  1990-11-30

    "belfold-1848-12":
        "archive_url_format": "https://24.hu/belfold/#year/#month/"

        "date_first_article": 1848-12-01
        "date_last_article":  1848-12-31

    "belfold-0001-01":
        "archive_url_format": "https://24.hu/belfold/#year/#month/"

        "date_first_article": 0001-01-01
        "date_last_article":  0001-01-31


"portal_specific_exctractor_functions_file": "../extractors/site_specific_extractor_functions_news_ngvmt.py"
"extract_next_page_url_fun": "extract_next_page_url_p24"
"extract_article_urls_from_page_fun": "extract_article_urls_from_page_p24"
"next_page_of_article_fun": "next_page_of_article_p24"
"extract_article_urls_from_page_plus_fun": "extract_article_urls_from_page_plus_p24"

"next_url_by_pagenum": false
"infinite_scrolling": false
"archive_page_urls_by_date": true
"go_reverse_in_archive": false
"verify_request": true
"ignore_archive_cache": false

# "new_article_url_threshold": 0

"corpus_converter_file": "../extractors/corpus_converters.py"
"corpus_converter": "MultiPageArticleConverter"
