"site_name": "p24"

"columns":
    # kultura - empty intervals are avoided with a pseudo-column.
    "kultura1":
        "archive_url_format": "https://24.hu/kultura/#year/#month/"

        "date_first_article": 2010-04-01
        "date_last_article":  2012-05-31

    "kultura2":
        "archive_url_format": "https://24.hu/kultura/#year/#month/#day/"

        "date_first_article": 2012-06-01
        "date_last_article":  2012-08-31

    "kultura3":
        "archive_url_format": "https://24.hu/kultura/#year/#month/"

        "date_first_article": 2012-09-01

    "kultura-0001-01":
        "archive_url_format": "https://24.hu/kultura/#year/#month/"

        "date_first_article": 0001-01-01
        "date_last_article":  0001-01-31

    # Problematic intervalls are separated and crawler with daily archive
    # to avoid the random ordering of articles with extactly matching date accross archive pages
    # elet-stilus - empty intervals are avoided with several pseudo-columns.
    "elet-stilus1":
        "archive_url_format": "https://24.hu/elet-stilus/#year/#month/"

        "date_first_article": 2001-02-01
        "date_last_article":  2005-05-31

    "elet-stilus2":
        "archive_url_format": "https://24.hu/elet-stilus/#year/#month/#day/"

        "date_first_article": 2005-06-01
        "date_last_article":  2010-12-31

    "elet-stilus3":
        "archive_url_format": "https://24.hu/elet-stilus/#year/#month/"

        "date_first_article": 2011-01-01

    "elet-stilus-2000-06":
        "archive_url_format": "https://24.hu/elet-stilus/#year/#month/"

        "date_first_article": 2000-06-01
        "date_last_article":  2000-06-30

    "elet-stilus-1956-10":
        "archive_url_format": "https://24.hu/elet-stilus/#year/#month/"

        "date_first_article": 1956-10-01
        "date_last_article":  1956-10-31

    "elet-stilus-1910-11":
        "archive_url_format": "https://24.hu/elet-stilus/#year/#month/"

        "date_first_article": 1910-11-01
        "date_last_article":  1910-11-30

    "elet-stilus-0001-01":
        "archive_url_format": "https://24.hu/elet-stilus/#year/#month/"

        "date_first_article": 0001-01-01
        "date_last_article":  0001-01-31

    # otthon.
    "otthon":
        "archive_url_format": "https://24.hu/otthon/#year/#month/"

        "date_first_article": 2017-05-01

    # The "europoli" column's articles link to articles in the main columns (e.g. belfold, kulfold, etc.).
    # No need to download these again.

    # The "velemeny" column's articles link to articles in the main columns (e.g. belfold, kulfold, etc.).
    # No need to download these again.

    # The "video" column's articles link to articles in the main columns (e.g. belfold, kulfold, etc.).
    # No need to download these again.

    # The "podcast" column's articles link to articles in the main columns (e.g. belfold, kulfold, etc.).
    # No need to download these again.

"portal_specific_exctractor_functions_file": "../extractors/site_specific_extractor_functions_news_ngvmt.py"
"extract_next_page_url_fun": "extract_next_page_url_p24"
"extract_article_urls_from_page_fun": "extract_article_urls_from_page_p24"
"next_page_of_article_fun": "next_page_of_article_p24"
"extract_article_urls_from_page_plus_fun": "extract_article_urls_from_page_plus_p24"

"next_url_by_pagenum": false
"infinite_scrolling": false
"archive_page_urls_by_date": true
"go_reverse_in_archive": false
"verify_request": true
"ignore_archive_cache": false

# "new_article_url_threshold": 0

"corpus_converter_file": "../extractors/corpus_converters.py"
"corpus_converter": "MultiPageArticleConverter"
