"site_name": "p24_sokszinuvidek"

# There are no columns on this site. This is an author-based schema.

"columns":
    "author-sokszinuvidek":
        "archive_url_format": "https://sokszinuvidek.24.hu/author/sokszinuvidek/"

    "author-vaskori":
        "archive_url_format": "https://sokszinuvidek.24.hu/author/vaskori/"

    "author-fekecse":
        "archive_url_format": "https://sokszinuvidek.24.hu/author/fekecse/"

    "author-vaskorm":
        "archive_url_format": "https://sokszinuvidek.24.hu/author/vaskorm/"

    "author-dobocsa":
        "archive_url_format": "https://sokszinuvidek.24.hu/author/dobocsa/"

    "author-kuno":
        "archive_url_format": "https://sokszinuvidek.24.hu/author/kuno/"

    "author-ardaya":
        "archive_url_format": "https://sokszinuvidek.24.hu/author/ardaya/"

    "author-duboczkyk":
        "archive_url_format": "https://sokszinuvidek.24.hu/author/duboczkyk/"

    "author-szponzoralt-tartalom":
        "archive_url_format": "https://sokszinuvidek.24.hu/author/szponzoralt-tartalom/"

"portal_specific_exctractor_functions_file": "../extractors/site_specific_extractor_functions_news_ngvmt.py"
"extract_next_page_url_fun": "extract_next_page_url_p24"
"extract_article_urls_from_page_fun": "extract_article_urls_from_page_p24"

"next_url_by_pagenum": false
"infinite_scrolling": false
"archive_page_urls_by_date": false
"go_reverse_in_archive": false
"verify_request": true
"ignore_archive_cache": false

# "new_article_url_threshold": 0

"corpus_converter_file": "../extractors/corpus_converters.py"
"corpus_converter": "dummy-converter"
