"site_name": "penzcsinalok_transindex"

"columns":
    "lokalis":
        "archive_url_format": "https://penzcsinalok.transindex.ro/lokalis/"

    "globalis":
        "archive_url_format": "https://penzcsinalok.transindex.ro/globalis/"

    "penzpiac":
        "archive_url_format": "https://penzcsinalok.transindex.ro/penzpiac/"

    "marketing":
        "archive_url_format": "https://penzcsinalok.transindex.ro/marketing/"

    "velemeny":
        "archive_url_format": "https://penzcsinalok.transindex.ro/velemeny/"

    "infografika":
        "archive_url_format": "https://penzcsinalok.transindex.ro/infografika/"


"portal_specific_exctractor_functions_file": "../extractors/site_specific_extractor_functions.py"
"extract_next_page_url_fun": "extract_next_page_url_lelato_penzcsinalok_transindex"
"extract_article_urls_from_page_fun": "extract_article_urls_from_page_lelato_penzcsinalok_transindex"

"next_url_by_pagenum": false
"infinite_scrolling": false
"archive_page_urls_by_date": false
"go_reverse_in_archive": false
"verify_request": true
"ignore_archive_cache": false

# "new_article_url_threshold": 0

"corpus_converter_file": "../extractors/corpus_converters.py"
"corpus_converter": "dummy-converter"
