"site_name": "penzcsinalok_transindex"

"columns":
    "lokalis":
        "archive_url_format": "https://penzcsinalok.transindex.ro/lokalis/#pagenum"

        "initial_pagenum": 1
        "min_pagenum": 2
        "max_pagenum": 20  # There are no articles displayed after page 20.

    "globalis":
        "archive_url_format": "https://penzcsinalok.transindex.ro/globalis/#pagenum"

        "initial_pagenum": 1
        "min_pagenum": 2
        "max_pagenum": 20  # There are no articles displayed after page 20.

    "penzpiac":
        "archive_url_format": "https://penzcsinalok.transindex.ro/penzpiac/#pagenum"

        "initial_pagenum": 1
        "min_pagenum": 2
        "max_pagenum": 19  # There are no articles displayed after page 19.

    "marketing":
        "archive_url_format": "https://penzcsinalok.transindex.ro/marketing/#pagenum"

        "initial_pagenum": 1
        "min_pagenum": 2
        "max_pagenum": 20  # There are no articles displayed after page 20.

    "velemeny":
        "archive_url_format": "https://penzcsinalok.transindex.ro/velemeny/#pagenum"

        "initial_pagenum": 1
        "min_pagenum": 2
        "max_pagenum": 4  # There are no articles displayed after page 4.

    "infografika":  # These articles contain only graphics, and no text.
        "archive_url_format": "https://penzcsinalok.transindex.ro/infografika/"

        "initial_pagenum": 1  # There are no articles displayed after page 1.

"portal_specific_exctractor_functions_file": "../extractors/site_specific_extractor_functions_htro.py"
"extract_article_urls_from_page_fun": "extract_article_urls_from_page_lelato_penzcsinalok_transindex"

"next_url_by_pagenum": true
"infinite_scrolling": false
"archive_page_urls_by_date": false
"go_reverse_in_archive": false
"verify_request": true
"ignore_archive_cache": false

# "new_article_url_threshold": 0

"corpus_converter_file": "../extractors/corpus_converters.py"
"corpus_converter": "dummy-converter"
