"site_name": "plakatmagany_transindex"

"columns":
    "main-column":
        "archive_url_format": "https://plakatmagany.transindex.ro/archivum/page/1/"

"portal_specific_exctractor_functions_file": "../extractors/htro_site_specific_extractor_functions.py"
"extract_next_page_url_fun": "extract_next_page_url_plakatmagany_transindex"
"extract_article_urls_from_page_fun": "extract_article_urls_from_page_plakatmagany_transindex"

"next_url_by_pagenum": false
"infinite_scrolling": false
"archive_page_urls_by_date": false
"go_reverse_in_archive": false
"verify_request": true
"ignore_archive_cache": false

# "new_article_url_threshold": 0

"corpus_converter_file": "../extractors/corpus_converters.py"
"corpus_converter": "dummy-converter"
