"site_name": "rangado_24hu"

# There are no columns on this site. This is an author-based schema.

"columns":
    "author-rangado":
        "archive_url_format": "https://rangado.24.hu/author/rangado/"

    "author-dajkab":
        "archive_url_format": "https://rangado.24.hu/author/dajkab/"

    "author-petop":
        "archive_url_format": "https://rangado.24.hu/author/petop/"

    "author-futocs":
        "archive_url_format": "https://rangado.24.hu/author/futocs/"

    "author-aranyossya":
        "archive_url_format": "https://rangado.24.hu/author/aranyossya/"

    "author-kalnokia":
        "archive_url_format": "https://rangado.24.hu/author/kalnokia/"

    "author-pincesil":
        "archive_url_format": "https://rangado.24.hu/author/pincesil/"


"portal_specific_exctractor_functions_file": "../extractors/site_specific_extractor_functions_news_ngvmt.py"
"extract_next_page_url_fun": "extract_next_page_url_24hu"
"extract_article_urls_from_page_fun": "extract_article_urls_from_page_rangado_sokszinuvidek_24hu"

"next_url_by_pagenum": false
"infinite_scrolling": false
"archive_page_urls_by_date": false
"go_reverse_in_archive": false
"verify_request": true
"ignore_archive_cache": false

# "new_article_url_threshold": 0

"corpus_converter_file": "../extractors/corpus_converters.py"
"corpus_converter": "MultiPageArticleConverter"
