"site_name": "roboraptor_24hu"

"columns":
    "film":
        "archive_url_format": "https://roboraptor.24.hu/film/"

    "sorozat":
        "archive_url_format": "https://roboraptor.24.hu/sorozat/"

    "konyv":
        "archive_url_format": "https://roboraptor.24.hu/konyv/"

    "podcast":
        "archive_url_format": "https://roboraptor.24.hu/tag/podcast/"

    "game":
        "archive_url_format": "https://roboraptor.24.hu/game/"

    "kepregeny":
        "archive_url_format": "https://roboraptor.24.hu/kepregeny/"

    "magazin":
        "archive_url_format": "https://roboraptor.24.hu/magazin/"


"portal_specific_exctractor_functions_file": "../extractors/site_specific_extractor_functions_news_ngvmt.py"
"extract_next_page_url_fun": "extract_next_page_url_24hu"
"extract_article_urls_from_page_fun": "extract_article_urls_from_page_istentudja_roboraptor_24hu"

"next_url_by_pagenum": false
"infinite_scrolling": false
"archive_page_urls_by_date": false
"go_reverse_in_archive": false
"verify_request": true
"ignore_archive_cache": false

# "new_article_url_threshold": 0

"corpus_converter_file": "../extractors/corpus_converters.py"
"corpus_converter": "dummy-converter"
