"site_name": "semmelweis"

"columns":
    "main-column":
        # Restricted to "koronavirus" tag
        "archive_url_format": "https://semmelweis.hu/hirek/tag/koronavirus/page/#pagenum/"

        # "date_first_article": 2020-03-02
        # "date_last_article": 2020-12-20

        "initial_pagenum": 1
        # "min_pagenum": 2
        # "max_pagenum": 7  There is an actual article at the last (8th) page of the archive!

"portal_specific_exctractor_functions_file": "../extractors/site_specific_extractor_functions.py"
"extract_next_page_url_fun": "extract_next_page_url_mosthallottam"
"extract_article_urls_from_page_fun": "extract_article_urls_from_page_semmelweis"

"next_url_by_pagenum": false
"infinite_scrolling": false
"archive_page_urls_by_date": false
"go_reverse_in_archive": true
"verify_request": false
"ignore_archive_cache": false

# "new_article_url_threshold": 0

"corpus_converter_file": "../extractors/corpus_converters.py"
"corpus_converter": "dummy-converter"
