"site_name": "sokszinuvidek_24hu"

"columns":
    "author-sokszinuvidek":
        "archive_url_format": "https://sokszinuvidek.24.hu/author/sokszinuvidek/"

    "author-vaskori":
        "archive_url_format": "https://sokszinuvidek.24.hu/author/vaskori/"

    "author-fekecse":
        "archive_url_format": "https://sokszinuvidek.24.hu/author/fekecse/"

    "author-vaskorm":
        "archive_url_format": "https://sokszinuvidek.24.hu/author/vaskorm/"

    "author-dobocsa":
        "archive_url_format": "https://sokszinuvidek.24.hu/author/dobocsa/"

    "author-kuno":
        "archive_url_format": "https://sokszinuvidek.24.hu/author/kuno/"

    "author-szponzoralt-tartalom":
        "archive_url_format": "https://sokszinuvidek.24.hu/author/szponzoralt-tartalom/"

"portal_specific_exctractor_functions_file": "../extractors/site_specific_extractor_functions.py"
"extract_next_page_url_fun": "extract_next_page_url_24hu"
"extract_article_urls_from_page_fun": "extract_article_urls_from_page_sokszinuvidek_24hu"

"next_url_by_pagenum": false
"infinite_scrolling": false
"archive_page_urls_by_date": false
"go_reverse_in_archive": false
"verify_request": true
"ignore_archive_cache": false

# "new_article_url_threshold": 0

"corpus_converter_file": "../extractors/corpus_converters.py"
"corpus_converter": "dummy-converter"
