"site_name": "szombat"

"columns":
    "main-column":
        "archive_url_format": "https://szombat.org/archiv?q=&y=#year&mo=#month"

    "date_first_article": 1989-11-01

"portal_specific_exctractor_functions_file": "../extractors/site_specific_extractor_functions_szng.py"
"extract_article_urls_from_page_fun": "extract_article_urls_from_page_szombat"
"extract_next_page_url_fun": "extract_next_page_url_szombat"

"next_url_by_pagenum": false
"infinite_scrolling": false
"archive_page_urls_by_date": true
"go_reverse_in_archive": false
"verify_request": true
"ignore_archive_cache": false

# "new_article_url_threshold": 0

"corpus_converter_file": "../extractors/corpus_converters.py"
"corpus_converter": "dummy-converter"