"site_name": "valasz"

"columns":
    "budapest":
        "archive_url_format": "http://valasz.hu/budapest?page=#pagenum"

        # "date_first_article": 2009-01-21
        # "date_last_article": 2100-01-01

        "initial_pagenum": 1
        "min_pagenum": 2
        "max_pagenum": 243

#    "budapest/pest-budai-latkep":
#        "archive_url_format": "http://valasz.hu/pest_budai_latkep?page=#pagenum"
#
#        "initial_pagenum": 1
#        "min_pagenum": 2
#        "max_pagenum": 162

    "gadasag":
        "archive_url_format": "http://valasz.hu/uzlet?page=#pagenum"

        "initial_pagenum": 1
        "min_pagenum": 2
        "max_pagenum": 1123

    "gazdasag/engeria":
        "archive_url_format": "http://valasz.hu/energia?page=#pagenum"

        "initial_pagenum": 1
        "min_pagenum": 2
        "max_pagenum": 2

    "gazdasag/europai-merce":
        "archive_url_format": "http://valasz.hu/europaimerce?page=#pagenum"

        "initial_pagenum": 1
        "min_pagenum": 2
        "max_pagenum": 3

    "gazdasag/gazdasagi mozaik":
        "archive_url_format": "http://valasz.hu/gazdasagimozaik?page=#pagenum"

        "initial_pagenum": 1
        "min_pagenum": 2
        "max_pagenum": 43

    "gazdasag/magyarok-a-piacon":
        "archive_url_format": "http://valasz.hu/magyarokapiacon?page=#pagenum"

        "initial_pagenum": 1
        "min_pagenum": 2
        "max_pagenum": 1

    "gazdasag/pr":
        "archive_url_format": "http://valasz.hu/pr?page=#pagenum"

        "initial_pagenum": 1
        "min_pagenum": 2
        "max_pagenum": 54

    "gazdasag/techvilag":
        "archive_url_format": "http://valasz.hu/techvilag?page=#pagenum"

        "initial_pagenum": 1
        "min_pagenum": 2
        "max_pagenum": 1

    "itthon":
        "archive_url_format": "http://valasz.hu/itthon?page=#pagenum"

        "initial_pagenum": 1
        "min_pagenum": 2
        "max_pagenum": 2341

#    "itthon/csalad":
#        "archive_url_format": "http://valasz.hu/csalad?page=#pagenum"
#
#        "initial_pagenum": 1
#        "min_pagenum": 2
#        "max_pagenum": 1
#
#    "itthon/eletmod":
#        "archive_url_format": "http://valasz.hu/eletmod?page=#pagenum"
#
#        "initial_pagenum": 1
#        "min_pagenum": 2
#        "max_pagenum": 187
#
#    "itthon/felsooktatasi-rangsor":
#        "archive_url_format": "http://valasz.hu/felsooktatasi_rangsor?page=#pagenum"
#
#        "initial_pagenum": 1
#        "min_pagenum": 2
#        "max_pagenum": 11
#
#    "itthon/reflektor":
#        "archive_url_format": "http://valasz.hu/reflektor?page=#pagenum"
#
#        "initial_pagenum": 1
#        "min_pagenum": 2
#        "max_pagenum": 86

    "kultura":
        "archive_url_format": "http://valasz.hu/kultura?page=#pagenum"

        "initial_pagenum": 1
        "min_pagenum": 2
        "max_pagenum": 1693

#    "kultura/esszencia":
#        "archive_url_format": "http://valasz.hu/esszencia?page=#pagenum"
#
#        "initial_pagenum": 1
#        "min_pagenum": 2
#        "max_pagenum": 11
#
#    "kultura/gasztronomia":
#        "archive_url_format": "http://valasz.hu/gasztronomia?page=#pagenum"
#
#        "initial_pagenum": 1
#        "min_pagenum": 2
#        "max_pagenum": 62
#
#    "kultura/kult-tura":
#        "archive_url_format": "http://valasz.hu/kult_tura?page=#pagenum"
#
#        "initial_pagenum": 1
#        "min_pagenum": 2
#        "max_pagenum": 1
#
#    "kultura/mozi":
#        "archive_url_format": "http://valasz.hu/mozi?page=#pagenum"
#
#        "initial_pagenum": 1
#        "min_pagenum": 2
#        "max_pagenum": 21
#
#    "kultura/sport":
#        "archive_url_format": "http://valasz.hu/sport?page=#pagenum"
#
#        "initial_pagenum": 1
#        "min_pagenum": 2
#        "max_pagenum": 437
#
#    "kultura/szinhaz":
#        "archive_url_format": "http://valasz.hu/szinhaz?page=#pagenum"
#
#        "initial_pagenum": 1
#        "min_pagenum": 2
#        "max_pagenum": 22

    "publi": # Publi column is special!
        "archive_url_format": "http://valasz.hu/publi?page=#pagenum"

        "initial_pagenum": 1
        "min_pagenum": 2
        "max_pagenum": 360

    "vilag":
        "archive_url_format": "http://valasz.hu/vilag?page=#pagenum"

        "initial_pagenum": 1
        "min_pagenum": 2
        "max_pagenum": 1453

#    "vilag/amerika-visszainteget":
#        "archive_url_format": "http://valasz.hu/amerika_visszainteget?page=#pagenum"
#
#        "initial_pagenum": 1
#        "min_pagenum": 2
#        "max_pagenum": 1

"portal_specific_exctractor_functions_file": "../extractors/site_specific_extractor_functions.py"
"extract_article_urls_from_page_fun": "extract_article_urls_from_page_valasz"

"next_url_by_pagenum": true
"infinite_scrolling": false
"archive_page_urls_by_date": false
"go_reverse_in_archive": true
"verify_request": true
"ignore_archive_cache": false

# "new_article_url_threshold": 0

"corpus_converter_file": "../extractors/corpus_converters.py"
"corpus_converter": "dummy-converter"
