"schema": "site_schemas/szekelyhon_schema.yaml"

# "output_corpus": "szekelyhon_corpus.txt"

"log_file_articles": "logs/szekelyhon_articles_log.txt"
"log_file_archive": "logs/szekelyhon_archive_log.txt"
"new_problematic_urls": "logs/szekelyhon_new_problematic_urls.txt"
"new_good_urls": "logs/szekelyhon_new_good_urls.txt"
"new_problematic_archive_urls": "logs/szekelyhon_new_problematic_archive_urls.txt"
"new_good_archive_urls": "logs/szekelyhon_new_good_archive_urls.txt"

# "date_from": 2015-08-20
# "date_until": 2020-12-17
