"schema": "site_schemas/utazomajom_schema.yaml"

# "output_corpus": "utazomajom_corpus.txt"

"log_file_articles": "logs/utazomajom_articles_log.txt"
"log_file_archive": "logs/utazomajom_archive_log.txt"
"new_problematic_urls": "logs/utazomajom_new_problematic_urls.txt"
"new_good_urls": "logs/utazomajom_new_good_urls.txt"
"new_problematic_archive_urls": "logs/utazomajom_new_problematic_archive_urls.txt"
"new_good_archive_urls": "logs/utazomajom_new_good_archive_urls.txt"

# "date_from": 2015-06-24
# "date_until": 2019-04-28
