"site_name": "index"
"site_schemas": "site_schemas.yaml"
"tags": "tags.yaml"

"create_corpus": true
"output_file": "index_corpus.txt"

"log_file_articles": "index_articles_log.txt"
"log_file_archive": "index_archive_log.txt"

# "date_from": 2000-01-01
# "date_until": 2100-01-01
