"schema": "site_schemas/bbeacon_schema.yaml"

# "output_corpus": "bbeacon_corpus.txt"

"log_file_articles": "logs/bbeacon_articles_log.txt"
"log_file_archive": "logs/bbeacon_archive_log.txt"
"new_problematic_urls": "logs/bbeacon_new_problematic_urls.txt"
"new_good_urls": "logs/bbeacon_new_good_urls.txt"
"new_problematic_archive_urls": "logs/bbeacon_new_problematic_archive_urls.txt"
"new_good_archive_urls": "logs/bbeacon_new_good_archive_urls.txt"

# "date_from": 2013-10-13
# "date_until": 2018-04-13
