"schema": "site_schemas/ujszo_schema.yaml"

# "output_corpus": "ujszo_corpus.txt"

"log_file_articles": "logs/ujszo_articles_log.txt"
"log_file_archive": "logs/ujszo_archive_log.txt"
"new_problematic_urls": "logs/ujszo_new_problematic_urls.txt"
"new_good_urls": "logs/ujszo_new_good_urls.txt"
"new_problematic_archive_urls": "logs/ujszo_new_problematic_archive_urls.txt"
"new_good_archive_urls": "logs/ujszo_new_good_archive_urls.txt"

# "date_from": 1970-01-01
# "date_until": 2021-05-03