"schema": "site_schemas/greenfo_schema.yaml"

# "output_corpus": "greenfo_corpus.txt"

"log_file_articles": "logs/greenfo_articles_log.txt"
"log_file_archive": "logs/greenfo_archive_log.txt"
"new_problematic_urls": "logs/greenfo_new_problematic_urls.txt"
"new_good_urls": "logs/greenfo_new_good_urls.txt"
"new_problematic_archive_urls": "logs/greenfo_new_problematic_archive_urls.txt"
"new_good_archive_urls": "logs/greenfo_new_good_archive_urls.txt"

# "date_from": 2001-01-26
