"schema": "site_schemas/telex_schema.yaml"

# "output_corpus": "telex_corpus.txt"

"log_file_articles": "logs/telex_articles_log.txt"
"log_file_archive": "logs/telex_archive_log.txt"
"new_problematic_urls": "logs/telex_new_problematic_urls.txt"
"new_good_urls": "logs/telex_new_good_urls.txt"
"new_problematic_archive_urls": "logs/telex_new_problematic_archive_urls.txt"
"new_good_archive_urls": "logs/telex_new_good_archive_urls.txt"

# "date_from": 2020-09-25
# "date_until": 2022-02-14
