"schema": "site_schemas/nlc_schema.yaml"

# "output_corpus": "nlc_corpus.txt"

"log_file_articles": "logs/nlc_articles_log.txt"
"log_file_archive": "logs/nlc_archive_log.txt"
"new_problematic_urls": "logs/nlc_new_problematic_urls.txt"
"new_good_urls": "logs/nlc_new_good_urls.txt"
"new_problematic_archive_urls": "logs/nlc_new_problematic_archive_urls.txt"
"new_good_archive_urls": "logs/nlc_new_good_archive_urls.txt"

# "date_from": 2015-08-20
# "date_until": 2020-12-17
