"schema": "site_schemas/feol_schema.yaml"

# "output_corpus": "feol_corpus.txt"

"log_file_articles": "logs/feol_articles_log.txt"
"log_file_archive": "logs/feol_archive_log.txt"
"new_problematic_urls": "logs/feol_new_problematic_urls.txt"
"new_good_urls": "logs/feol_new_good_urls.txt"
"new_problematic_archive_urls": "logs/feol_new_problematic_archive_urls.txt"
"new_good_archive_urls": "logs/feol_new_good_archive_urls.txt"
