"schema": "site_schemas/origo_schema.yaml"

# "output_corpus": "origo_corpus.txt"
# "tags": "tags.yaml"

"log_file_articles": "logs/origo_articles_log.txt"
"log_file_archive": "logs/origo_archive_log.txt"
"new_problematic_urls": "logs/origo_new_problematic_urls.txt"
"new_good_urls": "logs/origo_new_good_urls.txt"
"new_problematic_archive_urls": "logs/origo_new_problematic_archive_urls.txt"
"new_good_archive_urls": "logs/origo_new_good_archive_urls.txt"

# "date_from": 2000-01-01
# "date_until": 2100-01-01
