"schema": "site_schemas/kurucinfo_schema.yaml"

# "output_corpus": "kurucinfo_corpus.txt"

"log_file_articles": "logs/kurucinfo_articles_log.txt"
"log_file_archive": "logs/kurucinfo_archive_log.txt"
"new_problematic_urls": "logs/kurucinfo_new_problematic_urls.txt"
"new_good_urls": "logs/kurucinfo_new_good_urls.txt"
"new_problematic_archive_urls": "logs/kurucinfo_new_problematic_archive_urls.txt"
"new_good_archive_urls": "logs/kurucinfo_new_good_archive_urls.txt"

# "date_from": 2000-01-01
