"schema": "site_schemas/atlatszo_ro_schema.yaml"

# "output_corpus": "atlatszo_ro_corpus.txt"

"log_file_articles": "logs/atlatszo_ro_articles_log.txt"
"log_file_archive": "logs/atlatszo_ro_archive_log.txt"
"new_problematic_urls": "logs/atlatszo_ro_new_problematic_urls.txt"
"new_good_urls": "logs/atlatszo_ro_new_good_urls.txt"
"new_problematic_archive_urls": "logs/atlatszo_ro_new_problematic_archive_urls.txt"
"new_good_archive_urls": "logs/atlatszo_ro_new_good_archive_urls.txt"

# "date_from": 2015-08-20
# "date_until": 2020-12-17
