"schema": "site_schemas/index_koronavirus_schema.yaml"

# "output_corpus": "index_corpus.txt"

"log_file_articles": "logs/index_koronavirus_articles_log.txt"
"log_file_archive": "logs/index_koronavirus_archive_log.txt"
"new_problematic_urls": "logs/index_koronavirus_new_problematic_urls.txt"
"new_good_urls": "logs/index_koronavirus_new_good_urls.txt"
"new_problematic_archive_urls": "logs/index_koronavirus_new_problematic_archive_urls.txt"
"new_good_archive_urls": "logs/index_koronavirus_new_good_archive_urls.txt"

# "date_from": 2000-01-01
# "date_until": 2100-01-01
