"site_name": "mno"
"site_schemas": "site_schemas.yaml"
"tags": "tags.yaml"

"create_corpus": true
"output_file": "mno_belfold_corpus.txt"

"log_file_articles": "mno_belfold_articles_log.txt"
"log_file_archive": "mno_belfold_archive_log.txt"

# "date_from": 2000-01-01
# "date_until": 2100-01-01
