"schema": "site_schemas/kremmania_forum_schema.yaml"

# "output_corpus": "kremmania_forum_corpus.txt"

"log_file_articles": "logs/kremmania_forum_articles_log.txt"
"log_file_archive": "logs/kremmania_forum_archive_log.txt"
"new_problematic_urls": "logs/kremmania_forum_new_problematic_urls.txt"
"new_good_urls": "logs/kremmania_forum_new_good_urls.txt"
"new_problematic_archive_urls": "logs/kremmania_forum_new_problematic_archive_urls.txt"
"new_good_archive_urls": "logs/kremmania_forum_new_good_archive_urls.txt"

# "date_from":
# "date_until":
