"schema": "site_schemas/blikk_schema.yaml"

# "output_corpus": "blikk_corpus.txt"
# "tags": "tags.yaml"

"log_file_articles": "logs/blikk_articles_log.txt"
"log_file_archive": "logs/blikk_archive_log.txt"
"new_problematic_urls": "logs/blikk_new_problematic_urls.txt"
"new_good_urls": "logs/blikk_new_good_urls.txt"
"new_problematic_archive_urls": "logs/blikk_new_problematic_archive_urls.txt"
"new_good_archive_urls": "logs/blikk_new_good_archive_urls.txt"

# "date_from": 2009-01-21
# "date_until": 2018-03-22
