"schema": "site_schemas/lelato_transindex_schema.yaml"

# "output_corpus": "lelato_transindex_corpus.txt"

"log_file_articles": "logs/lelato_transindex_articles_log.txt"
"log_file_archive": "logs/lelato_transindex_archive_log.txt"
"new_problematic_urls": "logs/lelato_transindex_new_problematic_urls.txt"
"new_good_urls": "logs/lelato_transindex_new_good_urls.txt"
"new_problematic_archive_urls": "logs/lelato_transindex_new_problematic_archive_urls.txt"
"new_good_archive_urls": "logs/lelato_transindex_new_good_archive_urls.txt"

# "date_from": 2000-01-01
# "date_until": 2100-01-01
