"site_name": "444"
"site_schemas": "site_schemas.yaml"

# "output_corpus": "444_corpus.txt"
# "tags": "tags.yaml"

"log_file_articles": "logs/444_articles_log.txt"
"log_file_archive": "logs/444_archive_log.txt"
"new_problematic_urls": "logs/444_new_problematic_urls.txt"
"new_good_urls": "logs/444_new_good_urls.txt"
"new_problematic_archive_urls": "logs/444_new_problematic_archive_urls.txt"
"new_good_archive_urls": "logs/444_new_good_archive_urls.txt"

# "date_from": 2000-01-01
# "date_until": 2100-01-01
