"schema": "site_schemas/atv_schema.yaml"

# "output_corpus": "atv_corpus.txt"

"log_file_articles": "logs/atv_articles_log.txt"
"log_file_archive": "logs/atv_archive_log.txt"
"new_problematic_urls": "logs/atv_new_problematic_urls.txt"
"new_good_urls": "logs/atv_new_good_urls.txt"
"new_problematic_archive_urls": "logs/atv_new_problematic_archive_urls.txt"
"new_good_archive_urls": "logs/atv_new_good_archive_urls.txt"

# "date_from": 2014-09-17
# "date_until": 2019-12-31
