"schema": "site_schemas/pestisracok_schema.yaml"

# "output_corpus": "pestisracok_corpus.txt"

"log_file_articles": "logs/pestisracok_articles_log.txt"
"log_file_archive": "logs/pestisracok_archive_log.txt"
"new_problematic_urls": "logs/pestisracok_new_problematic_urls.txt"
"new_good_urls": "logs/pestisracok_new_good_urls.txt"
"new_problematic_archive_urls": "logs/pestisracok_new_problematic_archive_urls.txt"
"new_good_archive_urls": "logs/pestisracok_new_good_archive_urls.txt"
