"site_name": "444"
"site_schemas": "site_schemas.yaml"
"tags": "tags.yaml"

"create_corpus": true
"output_file": "444_corpus.txt"

"log_file_articles": "444_articles_log.txt"
"log_file_archive": "444_archive_log.txt"
"new_problematic_urls": NULL
"new_good_urls": NULL
"new_problematic_archive_urls": NULL
"new_good_archive_urls": NULL
"output_corpus": NULL

# "date_from": 2000-01-01
# "date_until": 2100-01-01
