"schema": "site_schemas/forumportfolio_schema.yaml"

# "output_corpus": "forumportfolio_corpus.txt"

"log_file_articles": "logs/forumportfolio_articles_log.txt"
"log_file_archive": "logs/forumportfolio_archive_log.txt"
"new_problematic_urls": "logs/forumportfolio_new_problematic_urls.txt"
"new_good_urls": "logs/forumportfolio_new_good_urls.txt"
"new_problematic_archive_urls": "logs/forumportfolio_new_problematic_archive_urls.txt"
"new_good_archive_urls": "logs/forumportfolio_new_good_archive_urls.txt"

# "date_from": 2011-12-31
# "date_until": 2021-04-26
