"schema": "site_schemas/24hu_schema.yaml"

# "output_corpus": "24hu_corpus.txt"

"log_file_articles": "logs/24hu_articles_log.txt"
"log_file_archive": "logs/24hu_archive_log.txt"
"new_problematic_urls": "logs/24hu_new_problematic_urls.txt"
"new_good_urls": "logs/24hu_new_good_urls.txt"
"new_problematic_archive_urls": "logs/24hu_new_problematic_archive_urls.txt"
"new_good_archive_urls": "logs/24hu_new_good_archive_urls.txt"

# "date_from": 2014-09-17
# "date_until": 2019-12-31
