"site_name": "blikk"
"site_schemas": "site_schemas.yaml"

# "output_corpus": "blikk_corpus.txt"
# "tags": "tags.yaml"

"log_file_articles": "blikk_articles_log.txt"
"log_file_archive": "blikk_archive_log.txt"
# "new_problematic_urls": NULL
# "new_good_urls": NULL
# "new_problematic_archive_urls": NULL
# "new_good_archive_urls": NULL

# "date_from": 2009-01-21
# "date_until": 2018-03-22
