"schema": "site_schemas/nepszava_schema.yaml"

# "output_corpus": "nepszava_corpus.txt"

"log_file_articles": "logs/nepszava_articles_log.txt"
"log_file_archive": "logs/nepszava_archive_log.txt"
"new_problematic_urls": "logs/nepszava_new_problematic_urls.txt"
"new_good_urls": "logs/nepszava_new_good_urls.txt"
"new_problematic_archive_urls": "logs/nepszava_new_problematic_archive_urls.txt"
"new_good_archive_urls": "logs/nepszava_new_good_archive_urls.txt"

# "date_from": 2010-12-01
# "date_until": 2010-12-06
