"schema": "site_schemas/hang_schema.yaml"

# "output_corpus": "hang_corpus.txt"

"log_file_articles": "logs/hang_articles_log.txt"
"log_file_archive": "logs/hang_archive_log.txt"
"new_problematic_urls": "logs/hang_new_problematic_urls.txt"
"new_good_urls": "logs/hang_new_good_urls.txt"
"new_problematic_archive_urls": "logs/hang_new_problematic_archive_urls.txt"
"new_good_archive_urls": "logs/hang_new_good_archive_urls.txt"

# "date_from": 2000-01-01
# "date_until": 2100-01-01
