"schema": "site_schemas/tv_transindex_schema.yaml"

# "output_corpus": "tv_transindex_corpus.txt"

"log_file_articles": "logs/tv_transindex_articles_log.txt"
"log_file_archive": "logs/tv_transindex_archive_log.txt"
"new_problematic_urls": "logs/tv_transindex_new_problematic_urls.txt"
"new_good_urls": "logs/tv_transindex_new_good_urls.txt"
"new_problematic_archive_urls": "logs/tv_transindex_new_problematic_archive_urls.txt"
"new_good_archive_urls": "logs/tv_transindex_new_good_archive_urls.txt"

# "date_from": 2000-01-01
# "date_until": 2100-01-01
