"origo":
    "date_first_article": 1998-12-01
    # "date_last_article":  2100-01-01
    "archive_url_format": "http://www.origo.hu/hir-archivum/#year/#year#month#day.html"

    "extract_next_page_url_fun": NULL
    "extract_article_urls_from_page_fun": "extract_article_urls_from_page_origo"
    "next_url_by_pagenum": false
    "infinite_scrolling": false
    "archive_page_urls_by_date": true
    "go_reverse_in_archive": true
    "verify": true

    "min_pagenum": 0
    # "max_pagenum": NULL

    "ignore_archive_cache": false
    # "new_article_url_threshold": 0
    "follow_links_on_page": false

    "corpus_converter": "rule-based"

    "tags_keys":
        "^http://www.origo\\.hu/": "origo-html"

"index":
    "date_first_article": 1999-06-30
    # "date_last_article":  2100-01-01
    "archive_url_format": "https://index.hu/24ora/?s=&tol=#year-#month-#day&ig=#year-#month-#day&tarskiadvanyokbanis=1&profil=&rovat=&cimke=&word=1&pepe=1&p=#pagenum"

    "extract_next_page_url_fun": NULL
    "extract_article_urls_from_page_fun": "extract_article_urls_from_page_index"
    "next_url_by_pagenum": true
    "infinite_scrolling": true
    "archive_page_urls_by_date": true
    "go_reverse_in_archive": true
    "verify": true

    "min_pagenum": 0
    # "max_pagenum": NULL

    "ignore_archive_cache": false
    # "new_article_url_threshold": 0
    "follow_links_on_page": false

    "corpus_converter": "rule-based"

    "tags_keys":
        "^https://index\\.hu/": "index-html"
        "^https://totalcar\\.hu/": "index-html"
        "^https://totalbike\\.hu/": "index-html"
        "^https://velvet\\.hu/": "index-html"
        "^https://divany\\.hu/": "divany-html"
        "^https://.*?\\.blog\\.hu/": "bloghu-html"
        "^https://galeria\\.(index|totalcar|totalbike|velvet|divany)\\.hu/": NULL

"velvet":
    "date_first_article": 2005-01-03
    # "date_last_article":  2100-01-01
    "archive_url_format": "https://velvet.hu/24ora/?s=&tol=#year-#month-#day&ig=#year-#month-#day&tarskiadvanyokbanis=1&profil=&rovat=&cimke=&word=1&pepe=1&p=#pagenum"

    "extract_next_page_url_fun": NULL
    "extract_article_urls_from_page_fun": "extract_article_urls_from_page_index"
    "next_url_by_pagenum": true
    "infinite_scrolling": true
    "archive_page_urls_by_date": true
    "go_reverse_in_archive": true
    "verify": true

    "min_pagenum": 0
    # "max_pagenum": NULL

    "ignore_archive_cache": false
    # "new_article_url_threshold": 0
    "follow_links_on_page": false

    "corpus_converter": "rule-based"

    "tags_keys":
        "^http://www\\.velvet\\.hu/": NULL

"blikk":
    "date_first_article": 2009-01-21
    # "date_last_article":  2100-01-01
    "archive_url_format": "http://www.blikk.hu/archivum/online?date=#year-#month-#day&page=#pagenum"

    "extract_next_page_url_fun": "extract_next_page_url_blikk"
    "extract_article_urls_from_page_fun": "extract_article_urls_from_page_blikk"
    "next_url_by_pagenum": false
    "infinite_scrolling": false
    "archive_page_urls_by_date": true
    "go_reverse_in_archive": true
    "verify": true

    "min_pagenum": 1
    # "max_pagenum": NULL

    "ignore_archive_cache": false
    # "new_article_url_threshold": 0
    "follow_links_on_page": false

    "corpus_converter": "rule-based"

    "tags_keys":
        "^http://www\\.blikk\\.hu/": "blikk-html"

"444":
    "date_first_article": 2013-04-10
    # "date_last_article":  2100-01-01
    "archive_url_format": "https://444.hu/#year/#month/#day/"

    "extract_next_page_url_fun": "extract_next_page_url_444"
    "extract_article_urls_from_page_fun": "extract_article_urls_from_page_444"
    "next_url_by_pagenum": true
    "infinite_scrolling": false
    "archive_page_urls_by_date": true
    "go_reverse_in_archive": true
    "verify": true

    "min_pagenum": 0
    # "max_pagenum": NULL

    "ignore_archive_cache": false
    # "new_article_url_threshold": 0
    "follow_links_on_page": false

    "corpus_converter": "rule-based"

    "tags_keys":
       "^https://444\\.hu/": "444-html"

"vs":
    "date_first_article": 2013-09-30
    "date_last_article": 2019-02-13
    "archive_url_format": "https://vs.hu/ajax/archive?Data={%22QueryString%22:%22%22,%22ColumnIds%22:[],%22SubcolumnIds%22:[],%22TagIds%22:[],%22HasPublicationMinFilter%22:true,%22PublicationMin%22:%22#year-#month-#dayT00:00:00.000Z%22,%22HasPublicationMaxFilter%22:true,%22PublicationMax%22:%22#next-year-#next-month-#next-dayT00:00:00.000Z%22,%22AuthorId%22:-1,%22MaxPublished%22:%22#next-year-#next-month-#next-dayT00:00:00.000Z%22,%22IsMega%22:false,%22IsPhoto%22:false,%22IsVideo%22:false}"

    "extract_next_page_url_fun": NULL
    "extract_article_urls_from_page_fun": "extract_article_urls_from_page_vs"
    "next_url_by_pagenum": false
    "infinite_scrolling": false
    "archive_page_urls_by_date": true
    "go_reverse_in_archive": true
    "verify": false

    "min_pagenum": 1
    # "max_pagenum": NULL

    "ignore_archive_cache": false
    # "new_article_url_threshold": 0
    "follow_links_on_page": false

    "corpus_converter": "rule-based"

    "tags_keys":
        "^http://www\\.vs\\.hu/": NULL

"mno":
    "date_first_article": 2009-01-21
    # "date_last_article": 2100-01-01
    "archive_url_format": "https://magyarnemzet.hu/archivum/page/#pagenum/"

    "extract_next_page_url_fun": "extract_next_page_url_mno"
    "extract_article_urls_from_page_fun": "extract_article_urls_from_page_mno"
    "next_url_by_pagenum": false
    "infinite_scrolling": false
    "archive_page_urls_by_date": false
    "go_reverse_in_archive": true
    "verify": true


    "initial_pagenum": 0
    "min_pagenum": 0
    # "max_pagenum": NULL

    "ignore_archive_cache": false
    # "new_article_url_threshold": 0
    "follow_links_on_page": false

    "corpus_converter": "rule-based"

    "tags_keys":
        "^https://mno\\.hu/": "mno-html"

"jogtar":
    "date_first_article": 1900-01-01
    # "date_last_article": 2100-01-01
    "archive_url_format": "https://net.jogtar.hu/jogszabaly-kereso?sorszam=&para=&tipus=&evszam=#year"

    "extract_next_page_url_fun": NULL
    "extract_article_urls_from_page_fun": NULL
    "next_url_by_pagenum": false
    "infinite_scrolling": false
    "archive_page_urls_by_date": true
    "go_reverse_in_archive": true
    "verify": true

    "min_pagenum": 0
    # "max_pagenum": NULL

    "ignore_archive_cache": false
    # "new_article_url_threshold": 0
    "follow_links_on_page": false

    "corpus_converter": "rule-based"

    "tags_keys":
        "^https://net\\.jogtar\\.hu/": NULL

"nol":
    "date_first_article": 1999-08-28
    # "date_last_article": 2016-04-15
    "archive_url_format": "http://nol.hu/archivum"

    "extract_next_page_url_fun": "extract_next_page_url_nol"
    "extract_article_urls_from_page_fun": "extract_article_urls_from_page_nol"
    "next_url_by_pagenum": true
    "infinite_scrolling": false
    "archive_page_urls_by_date": false
    "go_reverse_in_archive": true
    "verify": true

    "min_pagenum": 1
    "max_pagenum": 14671

    "ignore_archive_cache": false
    # "new_article_url_threshold": 0
    "follow_links_on_page": false

    "corpus_converter": "rule-based"

    "tags_keys":
        "^https://nol\\.hu/": "nol-html"

"valasz":
    # "date_first_article": 2009-01-21
    # "date_last_article": 2100-01-01
    "archive_url_format": "http://valasz.hu/reflektor/?page=#pagenum"

    "extract_next_page_url_fun": NULL
    "extract_article_urls_from_page_fun": "extract_article_urls_from_page_valasz"
    "next_url_by_pagenum": true
    "infinite_scrolling": false
    "archive_page_urls_by_date": false
    "go_reverse_in_archive": true
    "verify": true

    "initial_pagenum": 1
    "min_pagenum": 1
    "max_pagenum": 86

    "ignore_archive_cache": false
    # "new_article_url_threshold": 0
    "follow_links_on_page": false

    "corpus_converter": "rule-based"

    "tags_keys":
        "^http://valasz\\.hu/": "valasz-html"
