"origo":
    "date_first_article": 1998-12-01
    "archive_url_format": "http://www.origo.hu/hir-archivum/#year/#year#month#day.html"

    "article_url_format": "http://www\\.origo\\.hu/.*?\\.html"
    "before_article_url": "<h3><a href=\""
    "before_article_url_repl": ""
    "after_article_url": "\" title=\".*?\">.*?</a></h3>"
    "after_article_url_repl": ""

    "next_page_url_format": ""
    "before_next_page_url": ""
    "before_next_page_url_repl": ""
    "after_next_page_url": ""
    "after_next_page_url_repl": ""

    "article_date_format": ""
    "before_article_date": ""
    "before_article_date_repl": ""
    "after_article_date": ""
    "after_article_date_repl": ""
    "article_date_formatting": "%Y.%m.%d."

    "next_url_by_regex": true
    "next_url_by_pagenum": false
    "archive_page_urls_by_date": true
    "archive_page_urls_by_id": false
    "go_reverse_in_archive": true

    "min_pagenum": 0
    "max_pagenum": NULL
    "new_article_url_threshold": 0

    "tags_key": "origo-html"


"index":
    "date_first_article": 1999-06-30
    "archive_url_format": "https://index.hu/24ora/?s=&tol=#year-#month-#day&ig=#year-#month-#day&tarskiadvanyokbanis=1&profil=&rovat=&cimke=&word=1&pepe=1&p=#pagenum"

    "article_url_format": "https://.*?\\.hu/.*/"
    "before_article_url": "<h2 class=\"cim\"><a href=\""
    "before_article_url_repl": ""
    "after_article_url": "\">.*?</a></h2>"
    "after_article_url_repl": ""

    "next_page_url_format": ""
    "before_next_page_url": ""
    "before_next_page_url_repl": ""
    "after_next_page_url": ""
    "after_next_page_url_repl": ""

    "article_date_format": "[0-9]{4}\\.[0-9]{2}\\.[0-9]{2}\\."
    "before_article_date": "(s?)<div class=\"datum\">[ \n]*"
    "before_article_date_repl": ""
    "after_article_date": " [0-9]{2}:[0-9]{2} *</div>"
    "after_article_date_repl": ""
    "article_date_formatting": "%Y.%m.%d."

    "next_url_by_regex": false
    "next_url_by_pagenum": true
    "archive_page_urls_by_date": true
    "archive_page_urls_by_id": true
    "go_reverse_in_archive": true

    "min_pagenum": 0
    "max_pagenum": NULL
    "new_article_url_threshold": 0

    "tags_key": "index-html"

"index-warc":
    "tags_key": "index-warc"

"totalcar":
    "tags_key": "index-html"

"totalbike":
    "tags_key": "index-html"

"velvet":
    "tags_key": "index-html"

"divany":
    "tags_key": "divany-html"

"konyves.blog":
    "tags_key": "bloghu-html"

"homar.blog":
    "tags_key": "bloghu-html"

"comment.blog":
    "tags_key": "bloghu-html"

"blikk":
    "date_first_article": 2009-01-21
    "archive_url_format": "http://www.blikk.hu/archivum/online?date=#year-#month-#day&page=#pagenum"

    "article_url_format": "http://www\\.blikk\\.hu/.*?"
    "before_article_url": "<span class=\"archiveText\"><a href=\""
    "before_article_url_repl": ""
    "after_article_url": "\">"
    "after_article_url_repl": ""

    "next_page_url_format": ""
    "before_next_page_url": ""
    "before_next_page_url_repl": ""
    "after_next_page_url": ""
    "after_next_page_url_repl": ""

    "article_date_format": ""
    "before_article_date": ""
    "before_article_date_repl": ""
    "after_article_date": ""
    "after_article_date_repl": ""
    "article_date_formatting": "%Y.%m.%d."

    "next_url_by_regex": true
    "next_url_by_pagenum": false
    "archive_page_urls_by_date": true
    "archive_page_urls_by_id": true
    "go_reverse_in_archive": true

    "min_pagenum": 1
    "max_pagenum": NULL
    "new_article_url_threshold": 0

    "tags_key": "blikk-html"

"444":
    "date_first_article": 2013-04-10
    "archive_url_format": "https://444.hu/archivum?page="

    "article_url_format": "https://444\\.hu/[^\"]*?"
    "before_article_url": "(?s)<article class=\"card\">\\s*?<h3>\\s*?<a href=\""
    "before_article_url_repl": ""
    "after_article_url": "\">"
    "after_article_url_repl": ""

    "next_page_url_format": "https://444\\.hu/archivum\\?page=[0-9]+"
    "before_next_page_url": "<a href=\""
    "before_next_page_url_repl": ""
    "after_next_page_url": "\" class=\"infinity-next button\">Tovább a múltba</a>"
    "after_next_page_url_repl": ""

    "article_date_format": ""
    "before_article_date": ""
    "before_article_date_repl": ""
    "after_article_date": ""
    "after_article_date_repl": ""
    "article_date_formatting": "%Y.%m.%d."

    "next_url_by_regex": true
    "next_url_by_pagenum": false
    "archive_page_urls_by_date": false
    "archive_page_urls_by_id": true
    "go_reverse_in_archive": true

    "min_pagenum": 1
    "max_pagenum": NULL  # 2558 on 2019-01-23
    "new_article_url_threshold": 0

    "tags_key": "444-html"

"mno":
    "date_first_article": 2009-01-21
    "archive_url_format": "https://mno.hu/kereses/archivum/belfold/"

    "article_url_format": ".*?"
    "before_article_url": "<p class=\"szerzo\">.*?<h3><a href=\""
    "before_article_url_repl": ""
    "after_article_url": "\">"
    "after_article_url_repl": ""

    "next_page_url_format": ""
    "before_next_page_url": ""
    "before_next_page_url_repl": ""
    "after_next_page_url": ""
    "after_next_page_url_repl": ""

    "article_date_format": ""
    "before_article_date": ""
    "before_article_date_repl": ""
    "after_article_date": ""
    "after_article_date_repl": ""
    "article_date_formatting": "%Y.%m.%d."

    "next_url_by_regex": true
    "next_url_by_pagenum": false
    "archive_page_urls_by_date": false
    "archive_page_urls_by_id": true
    "go_reverse_in_archive": true

    "min_pagenum": 1
    "max_pagenum": NULL
    "new_article_url_threshold": 0

    "tags_key": "mno-html"

"jogtar":
    "date_first_article": 1900-01-01
    "archive_url_format": "https://net.jogtar.hu/jogszabaly-kereso?sorszam=&para=&tipus=&evszam=#year"

    "article_url_format": "/jogszabaly\\?docid=[^&]+"
    "before_article_url": "<a href=\""
    "before_article_url_repl": "https://net.jogtar.hu"
    "after_article_url": "&[^\"]*\">"
    "after_article_url_repl": ""

    "next_page_url_format": "/jogszabaly-kereso\\?[^\"]*evszam=[0-9]+&amp;pagenum=[0-9]+"
    "before_next_page_url": "<a rel=\"next\" href=\""
    "before_next_page_url_repl": "https://net.jogtar.hu"
    "after_next_page_url": "\">Következő&nbsp;&raquo;</a>"
    "after_next_page_url_repl": ""

    "article_date_format": ""
    "before_article_date": ""
    "before_article_date_repl": ""
    "after_article_date": ""
    "after_article_date_repl": ""
    "article_date_formatting": "%Y.%m.%d."

    "next_url_by_regex": true
    "next_url_by_pagenum": false
    "archive_page_urls_by_date": true
    "archive_page_urls_by_id": true
    "go_reverse_in_archive": true

    "min_pagenum": 0
    "max_pagenum": NULL
    "new_article_url_threshold": 0

    "tags_key": NULL
