"origo":
    "date_first_article": 1998-12-01
    "archive_url_format": "http://www.origo.hu/hir-archivum/#year/#year#month#day.html"

    "article_date_format": ""
    "before_article_date": ""
    "before_article_date_repl": ""
    "after_article_date": ""
    "after_article_date_repl": ""
    "article_date_formatting": "%Y.%m.%d."

    "extract_next_page_url_fun": NULL
    "extract_article_urls_from_page_fun": "extract_article_urls_from_page_origo"
    "next_url_by_pagenum": false
    "infinite_scrolling": false
    "archive_page_urls_by_date": true
    "archive_page_urls_by_id": false
    "ignore_archive_cache": false
    "go_reverse_in_archive": true
    "verify": true

    "min_pagenum": 0
    "max_pagenum": NULL
    "new_article_url_threshold": 0

    "corpus_converter": "rule-based"

    "tags_keys":
        "^http://www.origo\\.hu/": "origo-html"


"index":
    "date_first_article": 1999-06-30
    "archive_url_format": "https://index.hu/24ora/?s=&tol=#year-#month-#day&ig=#year-#month-#day&tarskiadvanyokbanis=1&profil=&rovat=&cimke=&word=1&pepe=1&p=#pagenum"

    "article_date_format": "[0-9]{4}\\.[0-9]{2}\\.[0-9]{2}\\."
    "before_article_date": "(s?)<div class=\"datum\">[ \n]*"
    "before_article_date_repl": ""
    "after_article_date": " [0-9]{2}:[0-9]{2} *</div>"
    "after_article_date_repl": ""
    "article_date_formatting": "%Y.%m.%d."

    "extract_next_page_url_fun": NULL
    "extract_article_urls_from_page_fun": "extract_article_urls_from_page_index"
    "next_url_by_pagenum": true
    "infinite_scrolling": true
    "archive_page_urls_by_date": true
    "archive_page_urls_by_id": false
    "ignore_archive_cache": false
    "go_reverse_in_archive": true
    "verify": true

    "min_pagenum": 0
    "max_pagenum": NULL
    "new_article_url_threshold": 0

    "corpus_converter": "rule-based"

    "tags_keys":
        "^https://index\\.hu/": "index-html"
        "^https://totalcar\\.hu/": "index-html"
        "^https://totalbike\\.hu/": "index-html"
        "^https://velvet\\.hu/": "index-html"
        "^https://divany\\.hu/": "divany-html"
        "^https://.*?\\.blog\\.hu/": "bloghu-html"
        "^https://galeria\\.(index|totalcar|totalbike|velvet|divany)\\.hu/": NULL

"blikk":
    "date_first_article": 2009-01-21
    "archive_url_format": "http://www.blikk.hu/archivum/online?date=#year-#month-#day&page=#pagenum"

    "article_date_format": ""
    "before_article_date": ""
    "before_article_date_repl": ""
    "after_article_date": ""
    "after_article_date_repl": ""
    "article_date_formatting": "%Y.%m.%d."

    "extract_next_page_url_fun": "extract_next_page_url_blikk"
    "extract_article_urls_from_page_fun": "extract_article_urls_from_page_blikk"
    "next_url_by_pagenum": false
    "infinite_scrolling": false
    "archive_page_urls_by_date": true
    "archive_page_urls_by_id": false
    "ignore_archive_cache": false
    "go_reverse_in_archive": true
    "verify": true

    "min_pagenum": 1
    "max_pagenum": NULL
    "new_article_url_threshold": 0

    "corpus_converter": "rule-based"

    "tags_keys":
        "^http://www\\.blikk\\.hu/": "blikk-html"

"444":
    "date_first_article": 2013-04-10
    "archive_url_format": "https://444.hu/#year/#month/#day/"

    "article_date_format": ""
    "before_article_date": ""
    "before_article_date_repl": ""
    "after_article_date": ""
    "after_article_date_repl": ""
    "article_date_formatting": "%Y.%m.%d."

    "extract_next_page_url_fun": "extract_next_page_url_444"
    "extract_article_urls_from_page_fun": "extract_article_urls_from_page_444"
    "next_url_by_pagenum": true
    "infinite_scrolling": false
    "archive_page_urls_by_date": true
    "archive_page_urls_by_id": false
    "ignore_archive_cache": false
    "go_reverse_in_archive": true
    "verify": true

    "min_pagenum": 0
    "max_pagenum": NULL
    "new_article_url_threshold": 0

    "corpus_converter": "rule-based"

    "tags_keys":
       "^https://444\\.hu/": "444-html"

"vs":
    "date_first_article": 2013-09-30
    "archive_url_format": "https://vs.hu/ajax/archive?Data={%22QueryString%22:%22%22,%22ColumnIds%22:[],%22SubcolumnIds%22:[],%22TagIds%22:[],%22HasPublicationMinFilter%22:true,%22PublicationMin%22:%22#year-#month-#dayT00:00:00.000Z%22,%22HasPublicationMaxFilter%22:true,%22PublicationMax%22:%22#next-year-#next-month-#next-dayT00:00:00.000Z%22,%22AuthorId%22:-1,%22MaxPublished%22:%22#next-year-#next-month-#next-dayT00:00:00.000Z%22,%22IsMega%22:false,%22IsPhoto%22:false,%22IsVideo%22:false}"

    "article_date_format": ""
    "before_article_date": ""
    "before_article_date_repl": ""
    "after_article_date": ""
    "after_article_date_repl": ""
    "article_date_formatting": "%Y.%m.%d."

    "extract_next_page_url_fun": NULL
    "extract_article_urls_from_page_fun": "extract_article_urls_from_page_vs"
    "next_url_by_pagenum": false
    "infinite_scrolling": false
    "archive_page_urls_by_date": true
    "archive_page_urls_by_id": false
    "ignore_archive_cache": false
    "go_reverse_in_archive": true

    "min_pagenum": 1
    "max_pagenum": NULL
    "new_article_url_threshold": 0

    "corpus_converter": "rule-based"

    "tags_keys":
        "^http://www\\.vs\\.hu/": NULL

"mno":
    "date_first_article": 2009-01-21
    "archive_url_format": "https://mno.hu/kereses/archivum/belfold/"

    "article_url_format": ".*?"
    "before_article_url": "<p class=\"szerzo\">.*?<h3><a href=\""
    "before_article_url_repl": ""
    "after_article_url": "\">"
    "after_article_url_repl": ""

    "next_page_url_format": ""
    "before_next_page_url": ""
    "before_next_page_url_repl": ""
    "after_next_page_url": ""
    "after_next_page_url_repl": ""

    "article_date_format": ""
    "before_article_date": ""
    "before_article_date_repl": ""
    "after_article_date": ""
    "after_article_date_repl": ""
    "article_date_formatting": "%Y.%m.%d."

    "next_url_by_regex": true
    "next_url_by_pagenum": false
    "archive_page_urls_by_date": false
    "archive_page_urls_by_id": true
    "ignore_archive_cache": false
    "go_reverse_in_archive": true
    "verify": true


    "min_pagenum": 1
    "max_pagenum": NULL
    "new_article_url_threshold": 0

    "tags_keys":
        "^https://mno\\.hu/": "mno-html"

"jogtar":
    "date_first_article": 1900-01-01
    "archive_url_format": "https://net.jogtar.hu/jogszabaly-kereso?sorszam=&para=&tipus=&evszam=#year"

    "article_url_format": "/jogszabaly\\?docid=[^&]+"
    "before_article_url": "<a href=\""
    "before_article_url_repl": "https://net.jogtar.hu"
    "after_article_url": "&[^\"]*\">"
    "after_article_url_repl": ""

    "next_page_url_format": "/jogszabaly-kereso\\?[^\"]*evszam=[0-9]+&amp;pagenum=[0-9]+"
    "before_next_page_url": "<a rel=\"next\" href=\""
    "before_next_page_url_repl": "https://net.jogtar.hu"
    "after_next_page_url": "\">Következő&nbsp;&raquo;</a>"
    "after_next_page_url_repl": ""

    "article_date_format": ""
    "before_article_date": ""
    "before_article_date_repl": ""
    "after_article_date": ""
    "after_article_date_repl": ""
    "article_date_formatting": "%Y.%m.%d."

    "next_url_by_regex": true
    "next_url_by_pagenum": false
    "archive_page_urls_by_date": true
    "archive_page_urls_by_id": true
    "ignore_archive_cache": false
    "go_reverse_in_archive": true
    "verify": true

    "min_pagenum": 0
    "max_pagenum": NULL
    "new_article_url_threshold": 0

    "tags_keys":
        "^https://net\\.jogtar\\.hu/": NULL

"nol":
    "date_first_article": 1900-01-01
    "archive_url_format": "http://nol.hu/archivum"

    "article_url_format": "http://nol.hu/[a-zA-Z]+/([a-z]+-)+([0-9]*-)*[0-9]+"
    "before_article_url": "<a class=\"vezetoCimkeAfter\" href=\""
    "before_article_url_repl": ""
    "after_article_url": "\">"
    "after_article_url_repl": ""

    "next_page_url_format": "/archivum\\?page=[0-9]+"
    "before_next_page_url": "(s?)<div class=\"next\">\\n\\s*<a\\s+href=\""
    "before_next_page_url_repl": "http://nol.hu"
    "after_next_page_url": "\">"
    "after_next_page_url_repl": ""

    "article_date_format": "[0-9]{4}\\.[0-9]{2}\\.[0-9]{2}\\."
    "before_article_date": "(s?)<div class=\"date\">[ \n]*"
    "before_article_date_repl": ""
    "after_article_date": " [0-9]{2}:[0-9]{2} *</div>"
    "after_article_date_repl": ""
    "article_date_formatting": "%Y.%m.%d."

    "next_url_by_regex": true
    "next_url_by_pagenum": true
    "archive_page_urls_by_date": false
    "archive_page_urls_by_id": true
    "ignore_archive_cache": false
    "go_reverse_in_archive": true

    "min_pagenum": 1
    "max_pagenum": 14671
    "new_article_url_threshold": 0

    "tags_keys":
        "^https://nol\\.hu/": "nol-html"
