"common":
    "article_begin_mark": "<docitem>\n"
    "article_end_mark": "</docitem>"

"index-warc":
    "warc-date":
        "open": "WARC-Date: "
        "inside": ".*?"
        "close": "\\n"

    "html-date":
        "open": "\\s*<meta name=\"i:publication\" content=\""
        "inside": ".*?"
        "close": "\" />"

    "warc-url":
        "open": "WARC-Target-URI: "
        "inside": ".*?"
        "close": "\\n"

    "html-url":
        "open": "\\s*<meta property=\"og:url\" content=\""
        "inside": ".*?"
        "close": "\" />"

    "warc-status_code":
        "open": "HTTP/1.1"
        "inside": ".*?"
        "close": "\\n"

    "warc-charset":
        "open": "Content-Type: .*?; charset="
        "inside": ".*?"
        "close": ";"

    "html-charset":
        "open": "\\s*<meta http-equiv=\"Content-type\" content=\".*?; charset="
        "inside": ".*?"
        "close": "\" />"

    "html-description":
        "open": "\\s*<meta property=\"og:description\" content=\""
        "inside": ".*?"
        "close": "\" />"

    "html-keywords":
        "open": "\\s*<meta name=\"keywords\" content=\""
        "inside": ".*?"
        "close": "\" />"

    "html-title":
        "open": "\\s*<meta property=\"og:title\" content=\""
        "inside": ".*?"
        "close": "\" />"

    "html-lead":
        "open": "<div class=\"lead\">"
        "inside": "(.|\\n)*?"
        "close": "</div>"

    "html-body":
        "open": "<div class=\"cikk-torzs\">"
        "inside": "(.|\\n)*?"
        "close": "<div class=\"social-stripe cikk-bottom-box\">"

"index-html":
    "html-date":
        "open": "\\s*<meta name=\"i:publication\" content=\""
        "inside": ".*?"
        "close": "\" />"

    "html-url":
        "open": "\\s*<meta property=\"og:url\" content=\""
        "inside": ".*?"
        "close": "\" />"

    "html-charset":
        "open": "\\s*<meta http-equiv=\"Content-type\" content=\".*?; charset="
        "inside": ".*?"
        "close": "\" />"

    "html-description":
        "open": "\\s*<meta property=\"og:description\" content=\""
        "inside": ".*?"
        "close": "\" />"

    "html-keywords":
        "open": "\\s*<meta name=\"keywords\" content=\""
        "inside": ".*?"
        "close": "\" />"

    "html-title":
        "open": "\\s*<meta property=\"og:title\" content=\""
        "inside": ".*?"
        "close": "\" />"

    "html-lead":
        "open": "<div class=\"lead\">"
        "inside": "(.|\\n)*?"
        "close": "</div>"

    "html-body":
        "open": "<div class=\"cikk-torzs\">"
        "inside": "(.|\\n)*?"
        "close": "<div class=\"social-stripe cikk-bottom-box\">"

"divany-html":
    "html-date":
        "open": "\\s*<meta name=\"i:publication\" content=\""
        "inside": ".*?"
        "close": "\" />"

    "html-url":
        "open": "\\s*<meta property=\"og:url\" content=\""
        "inside": ".*?"
        "close": "\" />"

    "html-charset":
        "open": "\\s*<meta http-equiv=\"Content-type\" content=\".*?; charset="
        "inside": ".*?"
        "close": "\" />"

    "html-description":
        "open": "\\s*<meta property=\"og:description\" content=\""
        "inside": ".*?"
        "close": "\" />"

    "html-keywords":
        "open": "\\s*<meta name=\"keywords\" content=\""
        "inside": ".*?"
        "close": "\" />"

    "html-title":
        "open": "\\s*<meta property=\"og:title\" content=\""
        "inside": ".*?"
        "close": "\" />"

    "html-lead":
        "open": "<b class=\"c-lead_text o-text o-text-size-base\">"
        "inside": "(.|\\n)*?"
        "close": "</b>"

    "html-body":
       "open": "<div class=\"e-article-body\">"
       "inside": "(.|\\n)*?"
       "close": "<div class=\"g-column-width-4 g-column-width-mid-small-4 g-column-width-medium-7 g-column-offset-left-medium-1\">"

"bloghu-html":
    "html-date":
        "open": "\\s*<meta name=\"i:publication\" content=\""
        "inside": ".*?"
        "close": "\" />"

    "html-url":
        "open": "\\s*<meta property=\"og:url\" content=\""
        "inside": ".*?"
        "close": "\" />"

    "html-charset":
        "open": "\\s*<meta http-equiv=\"Content-type\" content=\".*?; charset="
        "inside": ".*?"
        "close": "\" />"

    "html-description":
        "open": "\\s*<meta property=\"og:description\" content=\""
        "inside": ".*?"
        "close": "\" />"

    "html-keywords":
        "open": "\\s*<meta name=\"keywords\" content=\""
        "inside": ".*?"
        "close": "\" />"

    "html-title":
        "open": "\\s*<meta property=\"og:title\" content=\""
        "inside": ".*?"
        "close": "\" />"

    "html-lead":
        "open": "<b class=\"c-lead_text o-text o-text-size-base\">"
        "inside": "(.|\\n)*?"
        "close": "</b>"

    "html-body":
        "open": "<div class=\"entry\">"
        "inside": "(.|\\n)*?"
        "close": "<!--"

"origo-html":
    "html-date":
       "open": "<span id=\"article-date\" pubdate=\"pubdate\" datetime=\".*?\">"
       "inside": ".*?"
       "close": "</span>"

    "html-url":
        "open": "\\s*<meta property=\"og:url\" content=\""
        "inside": ".*?"
        "close": "\" />"

    "html-charset":
        "open": "<meta charset=\""
        "inside": ".*?"
        "close": "\">"

    "html-description":
        "open": "\\s*<meta property=\"og:description\" content=\""
        "inside": ".*?"
        "close": "\" />"

    "html-keywords":
        "open": "<div class=\"article-tags\">"
        "inside": ".*?"
        "close": "</div>"

    "html-title":
        "open": "\\s*<meta property=\"og:title\" content=\""
        "inside": ".*?"
        "close": "\" />"

    "html-lead":
        "open": "<div class=\"article-lead\">"
        "inside": "(.|\\n)*?"
        "close": "</div>"

    "html-body":
        "open": "</div>\\s*<p>"
        "inside": "(.|\\n)*?"
        "close": "(<div id=\"article-related\">|</article>)"

"blikk-html":
    "html-date":
        "open": "\\s*<div class=\"datePublished\">"
        "inside": ".*?"
        "close": "</div>"

    "html-url":
        "open": "<meta property=\"og:url\" content=\""
        "inside": ".*?"
        "close": "\" />"

    "html-charset":
        "open": "<meta charset=\""
        "inside": ".*?"
        "close": "\">"

    "html-description_lead":
        "open": "<meta property=\"og:description\" content=\""
        "inside": ".*?"
        "close": "\" />"

    "html-category":
        "open": "<h3 class=\"categoryName\">"
        "inside": ".*?"
        "close": "</h3>"

    "html-keywords":
        "open": "<section class=\"topTags\">\\s*<ul>\\s*<li><a href=\".*?\">"
        "inside": ".*?"
        "close": "</a></li>"

    "html-title":
        "open": "<meta property=\"og:title\" content=\""
        "inside": ".*?"
        "close": "\" />"

    "html-body":
        "open": "<div id=\"detail\" class=\"detail intext\" itemprop=\"articleBody\">"
        "inside": "(.|\\n)*?"
        "close": "(<div class=\"embeddedApp\">.*?)?<!-- sonda -->"

"444-html":
    "html-date":
        "open": "<meta property=\"article:published_time\" itemprop=\"datePublished\" content=\""
        "inside": ".*?"
        "close": "\" />"

    "html-url":
        "open": "<meta property=\"og:url\" content=\""
        "inside": ".*?"
        "close": "\">"

    "html-charset":
        "open": "<meta charset=\""
        "inside": ".*?"
        "close": "\">"

    "html-description_lead":
        "open": "<meta property=\"og:description\" content=\""
        "inside": ".*?"
        "close": "\">"

    "html-category":
        "open": "<li class=\"category\">\\s*?<a href=\".*?\">"
        "inside": ".*?"
        "close": "</a>"

    "html-keywords":
        "open": "<meta name=\"keywords\" content=\""
        "inside": ".*?"
        "close": "\" />"

    "html-title":
        "open": "<meta name=\"title\" content=\""
        "inside": ".*?"
        "close": "\" />"

    "html-body":
        "open": "<article>"
        "inside": "(.|\\n)*?"
        "close": "<footer class=\"hide-for-print\">"

"mno-html":
    "html-date":
        "open": "<p class=\"date\">"
        "inside": ".*?"
        "close": "</p>"

    "html-url":
        "open": "<meta property=\"og:url\" content=\""
        "inside": ".*?"
        "close": "\" >"

    "html-charset":
        "open": "<meta charset=\""
        "inside": ".*?"
        "close": "\" >"

    "html-description":
        "open": "<meta property=\"og:description\" content=\""
        "inside": ".*?"
        "close": "\" >"

    "html-lead":
        "open": "<div class=\"lead\">"
        "inside": ".*?"
        "close": "</div>"

    "html-category":
        "open": "\"articleSection\" : \""
        "inside": ".*?"
        "close": "\","

    "html-keywords":
        "open": "<meta name=\"keywords\" content=\""
        "inside": ".*?"
        "close": "\" >"

    "html-title":
        "open": "<meta name=\"title\" content=\""
        "inside": ".*?"
        "close": "\" >"

    "html-body":
        "open": "<div class=\"content hircikk clearfix\">"
        "inside": "(.|\\n)*?"
        "close": "</div>\\s*?<div class=\"content-footer\">"
