"site_name": "nol"
"site_schemas": "../site_schemas.yaml"

# "output_corpus": "nol_corpus.txt"
# "tags": "tags.yaml"

"log_file_articles": "logs/nol_belfold_articles_log.txt"
"log_file_archive": "logs/nol_belfold_archive_log.txt"
"new_problematic_urls": "logs/nol_belfold_new_problematic_urls.txt"
"new_good_urls": "logs/nol_belfold_new_good_urls.txt"
"new_problematic_archive_urls": "logs/nol_belfold_new_problematic_archive_urls.txt"
"new_good_archive_urls": "logs/nol_belfold_new_good_archive_urls.txt"

# "date_from": 2005-10-04
# "date_until": 2016-10-08

"archive_url_format": "http://nol.hu/belfold?page=#pagenum"
"max_pagenum": 3347
