"site_name": "nol"
"site_schemas": "../site_schemas.yaml"

# "output_corpus": "nol_corpus.txt"
# "tags": "tags.yaml"

"log_file_articles": "logs/nol_kulfold_articles_log.txt"
"log_file_archive": "logs/nol_kulfold_archive_log.txt"
"new_problematic_urls": "logs/nol_kulfold_new_problematic_urls.txt"
"new_good_urls": "logs/nol_kulfold_new_good_urls.txt"
"new_problematic_archive_urls": "logs/nol_kulfold_new_problematic_archive_urls.txt"
"new_good_archive_urls": "logs/nol_kulfold_new_good_archive_urls.txt"

# "date_from": 2008-09-02
# "date_until": 2016-10-07

"archive_url_format": "http://nol.hu/kulfold?page=#pagenum"
"max_pagenum": 2561
